import { env } from "./env";

type EmailTemplateSection = {
  label: string;
  value: string;
  emphasize?: boolean;
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function paragraphize(value: string) {
  return value
    .split(/\n{2,}/)
    .map(entry => entry.trim())
    .filter(Boolean);
}

function renderBodyParagraphs(text: string) {
  return paragraphize(text)
    .map(paragraph => `<p style="margin:0 0 14px;color:#3f3f46;font-size:15px;line-height:1.7;">${escapeHtml(paragraph).replaceAll("\n", "<br />")}</p>`)
    .join("");
}

function renderPlainTextSections(sections: EmailTemplateSection[]) {
  if (!sections.length) {
    return "";
  }

  return `\n\n${sections.map(section => `${section.label}: ${section.value}`).join("\n")}`;
}

export function renderTransactionalEmail(input: {
  title: string;
  intro?: string;
  body: string;
  ctaLabel?: string;
  ctaUrl?: string;
  sections?: EmailTemplateSection[];
  footerNote?: string;
}) {
  const sections = input.sections?.filter(section => section.value.trim()) ?? [];
  const footerNote = input.footerNote ?? "This message was generated by the Valley Farm operations platform.";
  const html = `<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;padding:0;background:#f6f2eb;font-family:Georgia,'Times New Roman',serif;">
    <div style="padding:32px 16px;">
      <div style="max-width:640px;margin:0 auto;background:#fffdf8;border:1px solid #eadfce;border-radius:24px;overflow:hidden;box-shadow:0 18px 42px rgba(68,54,34,0.08);">
        <div style="background:linear-gradient(135deg,#17351f 0%,#385d3d 100%);padding:28px 32px;color:#f8f6f0;">
          <div style="font-size:12px;letter-spacing:0.16em;text-transform:uppercase;opacity:0.82;">Valley Farm Operations</div>
          <h1 style="margin:12px 0 0;font-size:28px;line-height:1.2;">${escapeHtml(input.title)}</h1>
          ${input.intro ? `<p style="margin:12px 0 0;font-size:15px;line-height:1.6;opacity:0.92;">${escapeHtml(input.intro)}</p>` : ""}
        </div>
        <div style="padding:30px 32px 26px;">
          ${renderBodyParagraphs(input.body)}
          ${sections.length ? `
            <div style="margin:18px 0 22px;border:1px solid #e7dbc8;border-radius:18px;background:#fcfaf5;padding:18px 20px;">
              ${sections.map(section => `
                <div style="display:flex;justify-content:space-between;gap:16px;padding:8px 0;border-bottom:1px solid #efe5d7;">
                  <span style="color:#6b7280;font-size:13px;">${escapeHtml(section.label)}</span>
                  <span style="color:#111827;font-size:${section.emphasize ? "17px" : "14px"};font-family:${section.emphasize ? "'Courier New',monospace" : "inherit"};text-align:right;white-space:pre-wrap;word-break:break-word;">${escapeHtml(section.value)}</span>
                </div>
              `).join("").replace(/border-bottom:1px solid #efe5d7;(?=[\s\S]*$)/, "")}
            </div>
          ` : ""}
          ${input.ctaLabel && input.ctaUrl ? `
            <div style="margin-top:22px;">
              <a href="${escapeHtml(input.ctaUrl)}" style="display:inline-block;padding:13px 20px;border-radius:999px;background:#24452b;color:#fffdf8;text-decoration:none;font-size:14px;font-weight:600;">
                ${escapeHtml(input.ctaLabel)}
              </a>
            </div>
          ` : ""}
        </div>
        <div style="padding:18px 32px 26px;border-top:1px solid #efe5d7;color:#6b7280;font-size:12px;line-height:1.6;">
          ${escapeHtml(footerNote)}
        </div>
      </div>
    </div>
  </body>
</html>`;

  const text = [input.title, input.intro, input.body, renderPlainTextSections(sections), input.ctaUrl ? `${input.ctaLabel}: ${input.ctaUrl}` : null, footerNote]
    .filter((entry): entry is string => Boolean(entry))
    .join("\n\n");

  return {
    html,
    text,
  };
}

export function isEmailConfigured() {
  return Boolean(env.SMTP_HOST && env.SMTP_PORT && env.SMTP_USER && env.SMTP_PASS && env.SMTP_FROM_EMAIL);
}

export async function sendEmail(input: {
  to: string;
  subject: string;
  text: string;
  html?: string;
}) {
  if (!isEmailConfigured()) {
    throw new Error("SMTP is not configured.");
  }

  const nodemailer = await import("nodemailer");
  const transporter = nodemailer.createTransport({
    host: env.SMTP_HOST!,
    port: env.SMTP_PORT!,
    secure: env.SMTP_SECURE === "true",
    auth: {
      user: env.SMTP_USER!,
      pass: env.SMTP_PASS!,
    },
  });

  const fromName = env.SMTP_FROM_NAME?.trim();
  const from = fromName
    ? `"${fromName}" <${env.SMTP_FROM_EMAIL!}>`
    : env.SMTP_FROM_EMAIL!;

  return transporter.sendMail({
    from,
    to: input.to,
    subject: input.subject,
    text: input.text,
    html: input.html,
  });
}
