const price = (value: number) => (value > 0 ? value : null);

export type InventoryItem = {
  code: string;
  description: string;
  cashPrice: number | null;
  onlinePrice: number | null;
  availableInstore?: boolean;
};

export type InventoryCategory = {
  id: string;
  name: string;
  items: InventoryItem[];
};

export const inventory: InventoryCategory[] = [
  {
    id: "001",
    name: "Baby",
    items: [
      { code: "BABC", description: "Baby & Me Cream", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "EPX", description: "Epimax Cream 400g", cashPrice: price(5.5), onlinePrice: price(5.78) },
      { code: "HUGD", description: "Huggies Diapers - Pack", cashPrice: price(11.0), onlinePrice: price(11.55) },
      { code: "HUGW", description: "Huggies Wipes", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "JOH", description: "Johnson Jelly 325ml", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "JOHA", description: "Johnson Aqueous 350ml", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "JOHN", description: "Johnson Baby soap 175g", cashPrice: price(1.2), onlinePrice: price(1.26) },
      { code: "MASTW", description: "Masters Wipes", cashPrice: price(0), onlinePrice: price(0) },
      { code: "NAN", description: "Nan 1;2;3&4", cashPrice: price(5.5), onlinePrice: price(5.78) },
      { code: "PAMP", description: "Pampers Masters Pack", cashPrice: price(12.0), onlinePrice: price(12.6) },
      { code: "PAMPS", description: "Pampers Masters Single", cashPrice: price(0.12), onlinePrice: price(0.13) },
      { code: "PRED", description: "Predo  Wipes", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "PURA", description: "Purity Aqueous", cashPrice: price(2.3), onlinePrice: price(2.42) },
      { code: "SOFT", description: "Soft Care Pampers", cashPrice: price(5.0), onlinePrice: price(5.25) },
      { code: "SUNS", description: "Sunlight soap", cashPrice: price(0), onlinePrice: price(0) },
      { code: "SUPRDY", description: "Superdry - Pamper", cashPrice: price(0), onlinePrice: price(0) },
      { code: "WIP", description: "Wipes", cashPrice: price(0.7), onlinePrice: price(0.74) },
      { code: "WIPJOHN", description: "Johnson Wipes", cashPrice: price(0), onlinePrice: price(0) },
    ],
  },
  {
    id: "002",
    name: "Beverages",
    items: [
      { code: "ADE", description: "Shumba", cashPrice: null, onlinePrice: price(0.53) },
      { code: "AMAS", description: "AmaSip", cashPrice: null, onlinePrice: price(0.0) },
      { code: "AQA", description: "Aquaclear case", cashPrice: null, onlinePrice: price(4.2) },
      { code: "AQU", description: "Aquaclear 500ml", cashPrice: null, onlinePrice: price(0.35) },
      { code: "AQUA", description: "Aquaclear 750ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "BAL", description: "Ballyhouse lime/crush 2L", cashPrice: null, onlinePrice: price(2.63) },
      { code: "BALY", description: "Ballyhouse Ras/Blkbery", cashPrice: null, onlinePrice: price(2.1) },
      { code: "BAOJ01", description: "Baobab Juice -500ml", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BON", description: "Bonaqua", cashPrice: null, onlinePrice: price(0.35) },
      { code: "BONA", description: "Bonaqua Case", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BROTH", description: "Brothers Juice", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CAS", description: "Cascade 500ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CASC", description: "Cascade 1L", cashPrice: null, onlinePrice: price(1.05) },
      { code: "CERES", description: "Ceres 1L", cashPrice: null, onlinePrice: price(2.1) },
      { code: "CIT", description: "Citro Juice 1L", cashPrice: null, onlinePrice: price(1.05) },
      { code: "DEL", description: "Delta 1L", cashPrice: null, onlinePrice: price(0.0) },
      { code: "DELTA", description: "Delta 440ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "DETA", description: "DELTA 2L", cashPrice: null, onlinePrice: price(2.1) },
      { code: "DETM", description: "Delta 300ml", cashPrice: null, onlinePrice: price(0.35) },
      { code: "DRA", description: "Dragon", cashPrice: null, onlinePrice: price(1.05) },
      { code: "FIZ", description: "Fizzi 500ml", cashPrice: null, onlinePrice: price(0.0) },
      { code: "FIZZ", description: "Fizzi 2L", cashPrice: null, onlinePrice: price(1.05) },
      { code: "FRMIX", description: "Fresh-Up - 400ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "FRT", description: "Flava Burst 5L", cashPrice: null, onlinePrice: price(2.1) },
      { code: "FRU", description: "Fruitade", cashPrice: null, onlinePrice: price(1.58) },
      { code: "FRUG", description: "Frugo 300mls", cashPrice: null, onlinePrice: price(0.0) },
      { code: "FRUI", description: "Frutesca 430mls", cashPrice: null, onlinePrice: price(1.05) },
      { code: "FRUT", description: "Fruitade Guava", cashPrice: null, onlinePrice: price(0.0) },
      { code: "FRUTC", description: "Fruitcana", cashPrice: null, onlinePrice: price(0.53) },
      { code: "FUN", description: "Fun 'n Fresh", cashPrice: null, onlinePrice: price(1.37) },
      { code: "GINZNG", description: "Ginger Zinga", cashPrice: null, onlinePrice: price(0.0) },
      { code: "HNY", description: "HoneyPot", cashPrice: null, onlinePrice: price(0.0) },
      { code: "HNYPOT", description: "Honey Pot - Mahewu", cashPrice: null, onlinePrice: price(0.0) },
      { code: "JICP", description: "JuicyPlus Crush 5L", cashPrice: null, onlinePrice: price(0.0) },
      { code: "JUC", description: "Juice it 250ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "JUIPC", description: "Juicyplus 5L", cashPrice: null, onlinePrice: price(0.0) },
      { code: "KAMB", description: "Kambucha No.3", cashPrice: null, onlinePrice: price(1.05) },
      { code: "KAMBU", description: "Kambucha", cashPrice: null, onlinePrice: price(0.0) },
      { code: "KEF", description: "Kefalos Dairy/Juice 200ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "KEFALOS", description: "Milkit/ Juice Box", cashPrice: null, onlinePrice: price(12.6) },
      { code: "LIQ", description: "Liqui/Ceres Fruit Juice", cashPrice: null, onlinePrice: price(2.1) },
      { code: "MAM", description: "Mammoth Energy Drink", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MAZ", description: "Mazoe Orange 2L", cashPrice: null, onlinePrice: price(4.2) },
      { code: "MAZB", description: "Mazoe Blackberry 2L", cashPrice: null, onlinePrice: price(3.68) },
      { code: "MAZW", description: "Mazoe Mix", cashPrice: null, onlinePrice: price(3.15) },
      { code: "MIK", description: "Milkit Milkshake 100ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "MILKB01", description: "Milkit - Big", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MIN", description: "Minute Maid Original 400ml", cashPrice: null, onlinePrice: price(1.05) },
      { code: "MINU", description: "Minute Maid Refresh", cashPrice: null, onlinePrice: price(0.53) },
      { code: "MONTY", description: "Baked Beand Montys", cashPrice: null, onlinePrice: price(1.05) },
      { code: "MOY", description: "Mooyo Maheu", cashPrice: null, onlinePrice: price(0.0) },
      { code: "NATU", description: "Natural Joy - 1litre", cashPrice: null, onlinePrice: price(1.05) },
      { code: "ORAN", description: "Oran Crush 5L", cashPrice: null, onlinePrice: price(3.99) },
      { code: "PEAR", description: "Pearlenta Porridge 1kg", cashPrice: null, onlinePrice: price(1.58) },
      { code: "PEP", description: "Peps Case", cashPrice: null, onlinePrice: price(9.45) },
      { code: "PEPM", description: "PEPS 1L", cashPrice: null, onlinePrice: price(0.53) },
      { code: "PEPS", description: "Peps 500ml", cashPrice: null, onlinePrice: price(0.35) },
      { code: "PFK", description: "Pfuko Traditional 500ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "PFKBT", description: "Pfuko Buttermilk - 500ml", cashPrice: null, onlinePrice: price(0.63) },
      { code: "PFKO", description: "Pfuko case", cashPrice: null, onlinePrice: price(6.3) },
      { code: "PUREJ", description: "PureJoy Juice", cashPrice: null, onlinePrice: price(2.1) },
      { code: "PWR", description: "PowerPlus", cashPrice: null, onlinePrice: price(2.1) },
      { code: "QUEN", description: "Quench", cashPrice: null, onlinePrice: price(3.68) },
      { code: "RED", description: "RedBull", cashPrice: null, onlinePrice: price(1.26) },
      { code: "REV", description: "Revive juice 500ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "REVI", description: "Revive Maheu 500ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "REVJ", description: "Revive Juice 1L", cashPrice: null, onlinePrice: price(1.05) },
      { code: "REVM", description: "Revive Maheu 1L", cashPrice: null, onlinePrice: price(1.05) },
      { code: "RHD", description: "Rhodes Juice", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SQU", description: "Squish Squash Crush 2L", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SQUI", description: "Squish Squash Appl/Ras", cashPrice: null, onlinePrice: price(0.0) },
      { code: "STG", description: "Sting 500ml", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SUP", description: "SuperSip 500ml", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SUPD", description: "SuperDay 5L", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SWT", description: "Switch", cashPrice: null, onlinePrice: price(1.05) },
      { code: "UFRS", description: "Ufresh Maheu", cashPrice: null, onlinePrice: price(0.0) },
      { code: "UFSH", description: "Ufresh Drink", cashPrice: null, onlinePrice: price(0.0) },
      { code: "VIC", description: "Victoria Juice", cashPrice: null, onlinePrice: price(2.1) },
      { code: "WILDC01", description: "Wild Cat - 500ml", cashPrice: null, onlinePrice: price(0.53) },
    ],
  },
  {
    id: "003",
    name: "Cereals",
    items: [
      { code: "BOKO", description: "Bokomo CornFlakes", cashPrice: null, onlinePrice: price(3.68) },
      { code: "CER", description: "Cerelac 250g", cashPrice: null, onlinePrice: price(2.63) },
      { code: "CERE", description: "Cerelac 500ml", cashPrice: null, onlinePrice: price(5.25) },
      { code: "CEREV", description: "Cerevita 500g", cashPrice: null, onlinePrice: price(3.15) },
      { code: "CEREVM", description: "Cerevita Milk 500G", cashPrice: null, onlinePrice: price(4.2) },
      { code: "CERV", description: "Cerevita Sour", cashPrice: null, onlinePrice: price(2.63) },
      { code: "CON", description: "Cornflakes Kellogs 500g", cashPrice: null, onlinePrice: price(3.15) },
      { code: "COR", description: "CornFlakes Mamas", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CORN", description: "CornFLakes Willards", cashPrice: null, onlinePrice: price(2.31) },
      { code: "CORNBG", description: "Cornflakes Bigtree - 1kg", cashPrice: null, onlinePrice: price(4.2) },
      { code: "CORNBG02", description: "Cornflakes Bigtree - 500g", cashPrice: null, onlinePrice: price(2.42) },
      { code: "CORNFBG", description: "Cornflakes Bigtree - 750g", cashPrice: null, onlinePrice: price(3.36) },
      { code: "GRW", description: "Grown ups", cashPrice: null, onlinePrice: price(2.1) },
      { code: "KELCORNF", description: "Cornflakes Kellogs - 1kg", cashPrice: null, onlinePrice: price(4.73) },
      { code: "MUE", description: "Muesli", cashPrice: null, onlinePrice: price(3.68) },
      { code: "OAT", description: "Oats", cashPrice: null, onlinePrice: price(3.15) },
      { code: "SUN", description: "Sunny Porridge", cashPrice: null, onlinePrice: price(1.58) },
      { code: "WETBX", description: "Weetbix - 450g", cashPrice: null, onlinePrice: price(2.31) },
    ],
  },
  {
    id: "004",
    name: "Cleaning Products",
    items: [
      { code: "ALH", description: "Aloha Washing Pwd 2kg", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "ALO", description: "Aloha Washing Pwd 1kg", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "ALOD", description: "Aloha Dishwasher", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "ALOH", description: "Aloha Washing Pwdr 500g", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "ARP", description: "Arpic Cleaner 750ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "BIG", description: "BigBen bar", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "BOM", description: "Boom Paste", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "BOMFC", description: "Boom Force Cream 750ml", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "BOMM", description: "Boom 150g", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "BOMW", description: "Boom - 1KG", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "BOO", description: "BoomDish washer 750ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "BOOMB", description: "Boom Bleach 750ml", cashPrice: price(1.8), onlinePrice: price(1.89) },
      { code: "BOOMF", description: "Boom Force Scouring", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "BOOMM", description: "Boom W/P 500g", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "COB", description: "Cobra 350ml", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "COM", description: "Comfort 1L", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "DISW", description: "Dishwasher Seawave", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "DOMES", description: "Domestos local", cashPrice: price(0), onlinePrice: price(0) },
      { code: "DOMS", description: "Domestos", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "GK", description: "Gik 750ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "GREE", description: "Green Bar Perfection", cashPrice: price(1.3), onlinePrice: price(1.37) },
      { code: "GRN", description: "Green Bar", cashPrice: price(0), onlinePrice: price(0) },
      { code: "HAN", description: "Handy Andy", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "HARP", description: "Harpic", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "JK", description: "Jik 750ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "KIW", description: "Kiwi Polish 50ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "KNCK", description: "Knock Dishwasher 750ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "KNO", description: "Knockout Can", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "KNOA", description: "Knockout All Purpose Cleaner 500ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "KNOC", description: "Knock out Satchet", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "KNOCK", description: "Knockout Dishwasher 2L", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "KNOCT", description: "Knockout Bleach", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "KWI", description: "Kiwi 100ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "MAQ", description: "Maq 1kg", cashPrice: price(0), onlinePrice: price(0) },
      { code: "MEGFLR", description: "Boom 2kg", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "MQ", description: "Maq 2kg", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "NUGET", description: "Nugget - 100ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "OMO", description: "Omo Powder 2kg", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "PIN", description: "Pinegel 500ml", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "PNE", description: "Pinegel 1L", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "SEAW", description: "DishWasher Seawave 2L", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "SNL", description: "Sunlight Liquid", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "STASFT", description: "Star Soft - 2litre", cashPrice: price(3.5), onlinePrice: price(3.68) },
      { code: "STS", description: "StarSoft Refill mix", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "SUNL", description: "Sunlight 1kg", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "SUNLT", description: "SunLight Pwd 2kg", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "VIM", description: "Xtra Vim", cashPrice: price(0.8), onlinePrice: price(0.84) },
      { code: "VM", description: "Vim Can", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "XTRA", description: "XTRA Washing Powder", cashPrice: price(3.5), onlinePrice: price(3.68) },
    ],
  },
  {
    id: "005",
    name: "Cosmetics",
    items: [
      { code: "ADDSPRY", description: "Addidas Spray", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "AXP", description: "Axe Perfumer", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "BAB", description: "Baby Crez 500ml", cashPrice: price(1.8), onlinePrice: price(1.89) },
      { code: "BABL", description: "Baby line 500ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "BCS", description: "Black Chick  Small 125ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "BEV", description: "BeverlyHills Roll on", cashPrice: price(0), onlinePrice: price(0) },
      { code: "BEVP", description: "Beverly Hills Perfume", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "BLC", description: "BlackChic Big 250ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "BOD", description: "Bodi doc", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "BODD", description: "Bodi doc Tissue Oil", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "BOMO", description: "Boom Fabric Conditioner 2ltr", cashPrice: price(0), onlinePrice: price(0) },
      { code: "CBL", description: "Clere Beautiful Cream 400ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "CFM", description: "Clere For Men 450ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "CLG", description: "Clere Glycerine 100ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "CLM", description: "Clere Men lotion 400ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "CLR", description: "Clere Glyco Glycerine 100ml", cashPrice: price(1.2), onlinePrice: price(1.26) },
      { code: "CLRE", description: "Clere Ladies Cream", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "COSMO", description: "Cosmo Foam Bath", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "DAR", description: "Dark& Lovely", cashPrice: price(5.5), onlinePrice: price(5.78) },
      { code: "DAW", description: "Dawn", cashPrice: price(0), onlinePrice: price(0) },
      { code: "DAWN", description: "Dawn Cream", cashPrice: price(0), onlinePrice: price(0) },
      { code: "DAX31", description: "Dax 3 in 1 375mls", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "DAXG", description: "Dax Hair Grower 250ml", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "DAXH", description: "Dax Hair Grower 125mls", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "DAXI", description: "Dax Freez Big 250ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "DOVE", description: "Dove Lotion", cashPrice: price(5.5), onlinePrice: price(5.78) },
      { code: "DXA", description: "Dax Freez Small 100ml", cashPrice: price(1.2), onlinePrice: price(1.26) },
      { code: "DXB", description: "Dax Big 3 n 1", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "ENG", description: "English Blazer", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "EWP", description: "EasyWaves Pack", cashPrice: price(0), onlinePrice: price(0) },
      { code: "EXCLA", description: "Exclamation Perfume", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "GMG", description: "Gentel Magic lotion", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "GML", description: "Gentle Magic Cream", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "GMS", description: "Gentel Magic Serum", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "GNT", description: "Gentel Magic Soap", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "GNTO", description: "Gentle Magic Oil 50ml", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "HAR", description: "Hair Remover Cosmo 40g", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "HOIT", description: "Hoit Toity 90mls", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "HOITY", description: "Hoity Toity Lotion", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "IGM", description: "Ingrams Herbal", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "IGMS", description: "Ingrams Senstive 450ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "IMP", description: "Ingrams Moisture Plus 450ml", cashPrice: price(2.8), onlinePrice: price(2.94) },
      { code: "ING", description: "Ingrams men 450ml", cashPrice: price(2.8), onlinePrice: price(2.94) },
      { code: "INGM", description: "Ingrams Aloe 450ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "INGMS", description: "Ingrams tissue oi l450ml", cashPrice: price(3.5), onlinePrice: price(3.68) },
      { code: "INGRO", description: "Ingrams Original 450mls", cashPrice: price(2.8), onlinePrice: price(2.94) },
      { code: "INR", description: "Igrams Roibos 450ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "ISB", description: "Inecto Super Black75g", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "ISOP", description: "Isoplus Edge Control", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "ISP", description: "Iso Plus Hair Spry 240ml", cashPrice: price(1.8), onlinePrice: price(1.89) },
      { code: "LACE", description: "Lace Lotion", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "MOUS", description: "Mousse", cashPrice: price(0), onlinePrice: price(0) },
      { code: "NIV", description: "Nivea Cream/Lotion 400ml", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "NIVA", description: "Nivea Radiant Cream 400ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "NIVES", description: "Nivea Spray", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "NVIA", description: "Nivea Q10", cashPrice: price(7.5), onlinePrice: price(7.88) },
      { code: "OHS", description: "Oh So Heavenly Lotion 720ml", cashPrice: price(5.0), onlinePrice: price(5.25) },
      { code: "OHSHV", description: "Oh So Heavenly - 2L", cashPrice: price(5.5), onlinePrice: price(5.78) },
      { code: "OHSL", description: "Oh  So Heavenly Lotion 1L", cashPrice: price(7.0), onlinePrice: price(7.35) },
      { code: "OHSO", description: "Oh SO Heavenly Cream 450ml", cashPrice: price(4.0), onlinePrice: price(4.2) },
      { code: "OHSOQ", description: "Oh So heavenly Q10", cashPrice: price(7.0), onlinePrice: price(7.35) },
      { code: "OLV", description: "Olive Oil Spry 250ml", cashPrice: price(1.8), onlinePrice: price(1.89) },
      { code: "PLA", description: "PlayBoy Roll on", cashPrice: price(0), onlinePrice: price(0) },
      { code: "PLAY", description: "PlayBoy Perfume", cashPrice: price(0), onlinePrice: price(0) },
      { code: "RLS", description: "Roll On Shield", cashPrice: price(0), onlinePrice: price(0) },
      { code: "ROLL", description: "Roll On Addidas 50ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "ROLNIV", description: "Roll on Nivea - 50ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "ROP", description: "Roll On Power House 50ml", cashPrice: price(0), onlinePrice: price(0) },
      { code: "SHOW", description: "Shower To Shower", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "SHWR", description: "Shower to Shower Perfume", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "SKA", description: "Skala 200g", cashPrice: price(0), onlinePrice: price(0) },
      { code: "SKAL", description: "Skala hairFood", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "TOPS", description: "Top Society", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "VAS", description: "Vaseline 450ml", cashPrice: price(3.8), onlinePrice: price(3.99) },
      { code: "VASE", description: "Vaseline 250ml", cashPrice: price(2.0), onlinePrice: price(2.1) },
      { code: "VASEL", description: "v", cashPrice: price(0), onlinePrice: price(0) },
      { code: "VASELN", description: "Vaseline lips", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "VASL", description: "Vaseline 50ml", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "VASLN", description: "Vaseline Cream", cashPrice: price(3.0), onlinePrice: price(3.15) },
      { code: "VASLNL", description: "Vaseline Lotion", cashPrice: price(3.5), onlinePrice: price(3.68) },
      { code: "VESTGLC", description: "Vestline Garlic - 200g", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "VSN", description: "Vaseline - 100ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
    ],
  },
  {
    id: "019",
    name: "Toiletries",
    items: [
      { code: "ANG", description: "Angel Care Tissue", cashPrice: price(8.0), onlinePrice: price(8.4) },
      { code: "AQFRSH", description: "Aquafresh - 100ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "BABYS", description: "Baby Soft 18s", cashPrice: price(9.5), onlinePrice: price(9.98) },
      { code: "CLO", description: "Close Up", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "COL", description: "Colgate 100ml", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "DELLP", description: "Utra Pads", cashPrice: price(0.6), onlinePrice: price(0.63) },
      { code: "DETO", description: "Dettol Liquid", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "DETT", description: "Dettol soap", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "GEI", description: "Geisha", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "HIL", description: "HiLife Soap", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "HYG", description: "hygienix Soap 175g", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "JAD", description: "Jade Soap", cashPrice: price(0.8), onlinePrice: price(0.84) },
      { code: "KOT", description: "Kotex pads 10s", cashPrice: price(1.5), onlinePrice: price(1.58) },
      { code: "LIFBY", description: "Lifebouy", cashPrice: price(0.8), onlinePrice: price(0.84) },
      { code: "LUX", description: "Lux Soap", cashPrice: price(0.9), onlinePrice: price(0.95) },
      { code: "OHSOH", description: "Oh So Heavenly Gel", cashPrice: price(0), onlinePrice: price(0) },
      { code: "PANT", description: "Kotex Pant Liners", cashPrice: price(0), onlinePrice: price(0) },
      { code: "PDS", description: "Pads Mix", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "PERI", description: "Period pants", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "PROT", description: "Protex Soap", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "PRVT", description: "Private Joy Tissue", cashPrice: price(8.0), onlinePrice: price(8.4) },
      { code: "ROM", description: "Romance Soap 50g", cashPrice: price(0.8), onlinePrice: price(0.84) },
      { code: "SAT", description: "Tissue Single", cashPrice: price(0.5), onlinePrice: price(0.53) },
      { code: "SATI", description: "Satiskin 2L", cashPrice: price(4.5), onlinePrice: price(4.73) },
      { code: "SATSK", description: "Satiskin 1L", cashPrice: price(2.5), onlinePrice: price(2.63) },
      { code: "SON", description: "Sona", cashPrice: price(0), onlinePrice: price(0) },
      { code: "TISS", description: "Tissue 4s", cashPrice: price(1.0), onlinePrice: price(1.05) },
      { code: "TWIN", description: "TwinSaver Tissue", cashPrice: price(9.0), onlinePrice: price(9.45) },
      { code: "TWINS", description: "TwinSaver 9s", cashPrice: price(4.5), onlinePrice: price(4.73) },
      { code: "YBO", description: "Yebo Soap", cashPrice: price(0.5), onlinePrice: price(0.53) },
    ],
  },
  {
    id: "012",
    name: "Snack",
    items: [
      { code: "ALL", description: "Allsorts sweets", cashPrice: null, onlinePrice: price(1.05) },
      { code: "AMAZ", description: "Amazon Cookies", cashPrice: null, onlinePrice: price(0.53) },
      { code: "BIC", description: "Bickies", cashPrice: null, onlinePrice: price(0.42) },
      { code: "BLS01", description: "Bliss - 200g", cashPrice: null, onlinePrice: price(0.42) },
      { code: "BUBB", description: "Bubble Chocolate", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CAK", description: "Cake", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CARD", description: "Cardbury choc", cashPrice: null, onlinePrice: price(1.58) },
      { code: "CHA", description: "Charhons 500g", cashPrice: null, onlinePrice: price(1.58) },
      { code: "CHAR", description: "Charhons 1kg", cashPrice: null, onlinePrice: price(3.15) },
      { code: "CHARH", description: "Charhorns 2kg", cashPrice: null, onlinePrice: price(5.46) },
      { code: "CHARHN", description: "Charhon Crunch Cookies", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHARNS", description: "Charhons 200g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CHCOK", description: "Charhons Cookies - 500g", cashPrice: null, onlinePrice: price(1.58) },
      { code: "CHELS", description: "ShortBread Chelsea", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CHI", description: "Chicken curls", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHIC", description: "Chicken Flings", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHMP", description: "Chompkins 25g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHO", description: "Chocolate Coated Biscuits", cashPrice: null, onlinePrice: price(1.58) },
      { code: "CHOCC", description: "Chocalate Coated Small", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CHOCCB", description: "Chocolate coated Box", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHOI", description: "Choice Biscuits", cashPrice: null, onlinePrice: price(1.58) },
      { code: "CHOMP", description: "Chompkins 150g", cashPrice: null, onlinePrice: price(1.37) },
      { code: "CHPP", description: "Chippa", cashPrice: null, onlinePrice: price(0.0) },
      { code: "COC", description: "Coco Bongo Choc", cashPrice: null, onlinePrice: price(0.0) },
      { code: "COKI", description: "Cookies", cashPrice: null, onlinePrice: price(0.53) },
      { code: "COU", description: "Cough drops", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CRAC", description: "Cracker Jax", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CRINK", description: "Crinkles big", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CRM", description: "CreamFeast", cashPrice: null, onlinePrice: price(0.0) },
      { code: "DAI", description: "Daisy Biscuits", cashPrice: null, onlinePrice: price(0.53) },
      { code: "DAND", description: "Dandy Pack", cashPrice: null, onlinePrice: price(2.63) },
      { code: "DELL", description: "Dell Cookies 500ml", cashPrice: null, onlinePrice: price(1.89) },
      { code: "DELLC", description: "Dell cookies 1kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "DOR", description: "Doritos 145g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "ECLAI", description: "Eclair/Big Boom Pack", cashPrice: null, onlinePrice: price(3.47) },
      { code: "ELD30", description: "Eldos - 30g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "FIN", description: "Finger Biscuits", cashPrice: null, onlinePrice: price(0.53) },
      { code: "FRI", description: "Frimax 150g", cashPrice: null, onlinePrice: price(1.58) },
      { code: "FUNN", description: "Funny Dip", cashPrice: null, onlinePrice: price(0.21) },
      { code: "GOLD", description: "GoldenFresh Biscuits", cashPrice: null, onlinePrice: price(0.0) },
      { code: "HAL01", description: "HALLS", cashPrice: null, onlinePrice: price(0.11) },
      { code: "HELL", description: "Hello/Chippa Single", cashPrice: null, onlinePrice: price(0.53) },
      { code: "HELPCK", description: "Hello - Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "IMPR", description: "Imperial Mints", cashPrice: null, onlinePrice: price(1.05) },
      { code: "JMBO", description: "Jumbo Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "JOE", description: "Joe Biscuits", cashPrice: null, onlinePrice: price(0.35) },
      { code: "JPT", description: "Jupiter 75g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "JUMSNG", description: "Jumbo single", cashPrice: null, onlinePrice: price(0.0) },
      { code: "KING", description: "KingKurls Pack", cashPrice: null, onlinePrice: price(3.68) },
      { code: "KIS01", description: "Kiss", cashPrice: null, onlinePrice: price(0.0) },
      { code: "KNG", description: "KingKurls Single", cashPrice: null, onlinePrice: price(0.53) },
      { code: "KRE", description: "Krema Biscuits", cashPrice: null, onlinePrice: price(0.0) },
      { code: "LAKK", description: "LakkerNax", cashPrice: null, onlinePrice: price(1.89) },
      { code: "LAYS", description: "Lays 125g", cashPrice: null, onlinePrice: price(1.58) },
      { code: "LOB", description: "Lobels Biscuits", cashPrice: null, onlinePrice: price(0.53) },
      { code: "LOBE", description: "Lobels Loose Biscuits", cashPrice: null, onlinePrice: price(0.0) },
      { code: "LOLI", description: "Lollipop", cashPrice: null, onlinePrice: price(0.21) },
      { code: "LOO", description: "Loose Biscuits 200g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "LOS", description: "Loose Buiscuits 2kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "LUN", description: "Lunch Bar Choc", cashPrice: null, onlinePrice: price(0.42) },
      { code: "LYS", description: "Lays 23g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MAP", description: "Maputi", cashPrice: null, onlinePrice: price(1.05) },
      { code: "MARIE", description: "Marie", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MARS", description: "MarshMallow Long", cashPrice: null, onlinePrice: price(0.26) },
      { code: "MARSH", description: "MarshMallow Long Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MAY", description: "Maynards Jelly Sweets", cashPrice: null, onlinePrice: price(1.05) },
      { code: "MINTS", description: "Mints Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MNT", description: "Mint/Dandy/toffe", cashPrice: null, onlinePrice: price(0.05) },
      { code: "MPT", description: "Maputi Authentic", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MRSHP", description: "MarshMallow Pack", cashPrice: null, onlinePrice: price(6.3) },
      { code: "NIB", description: "Nibbles", cashPrice: null, onlinePrice: price(0.0) },
      { code: "NIVE", description: "Maputi Single", cashPrice: null, onlinePrice: price(0.11) },
      { code: "PAS", description: "Pascal Choc", cashPrice: null, onlinePrice: price(0.53) },
      { code: "POP", description: "Popcorn", cashPrice: null, onlinePrice: price(1.05) },
      { code: "POPCN", description: "Popticorn -120g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "POPT", description: "Popticorn Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "PRO", description: "Proton Cookies 1kg", cashPrice: null, onlinePrice: price(3.68) },
      { code: "PROTN", description: "Proton Cookies 250g", cashPrice: null, onlinePrice: price(1.05) },
      { code: "PROTO", description: "Proton Cookies 2kg", cashPrice: null, onlinePrice: price(6.83) },
      { code: "PRT", description: "Proton Cookies 500g", cashPrice: null, onlinePrice: price(2.1) },
      { code: "RIPP", description: "Ripples", cashPrice: null, onlinePrice: price(1.05) },
      { code: "ROSS", description: "Rosso Chocolate", cashPrice: null, onlinePrice: price(0.0) },
      { code: "ROSY", description: "Rossy Wafers", cashPrice: null, onlinePrice: price(0.53) },
      { code: "RUL", description: "Rul 3D", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SHOR", description: "ShortBread Mini", cashPrice: null, onlinePrice: price(0.26) },
      { code: "SHRT", description: "ShortBread Biscuits - 150g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SIM", description: "Simba", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SPD", description: "Spuds 30g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SPNRL01", description: "Spinners loose - Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SPU", description: "Spuds 75g", cashPrice: null, onlinePrice: price(1.05) },
      { code: "SPUD", description: "Spuds/Lays Box 30g", cashPrice: null, onlinePrice: price(10.5) },
      { code: "SPUDB", description: "S", cashPrice: null, onlinePrice: price(0.0) },
      { code: "STA", description: "Stambo/ BigBoom Pack", cashPrice: null, onlinePrice: price(3.15) },
      { code: "STAMB", description: "Stambo/ BigBoom Single", cashPrice: null, onlinePrice: price(0.11) },
      { code: "SUNB", description: "SunBite Biscuits", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SUNSA", description: "Sun Snack", cashPrice: null, onlinePrice: price(0.53) },
      { code: "SWEE", description: "Sweet Cup", cashPrice: null, onlinePrice: price(0.11) },
      { code: "SWEEC", description: "SweetCup Can", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TEA", description: "Tea Biscuits", cashPrice: null, onlinePrice: price(3.15) },
      { code: "THI", description: "Things/Kornkurl 150g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "THIN", description: "Things 75g", cashPrice: null, onlinePrice: price(1.05) },
      { code: "THING", description: "Things Pack", cashPrice: null, onlinePrice: price(5.25) },
      { code: "THINP", description: "THINGS Pack", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TME", description: "Time Biscuits", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TOF", description: "Toffee Bar", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TOPTB", description: "Top T biscuits - 150g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TORK", description: "Torku Chocolate", cashPrice: null, onlinePrice: price(0.26) },
      { code: "VIG", description: "Vigos Choc", cashPrice: null, onlinePrice: price(0.11) },
      { code: "WSH", description: "Wish Cream", cashPrice: null, onlinePrice: price(1.05) },
      { code: "YOGT", description: "Yogurt Kefalos 75ml", cashPrice: null, onlinePrice: price(0.63) },
      { code: "ZAP", description: "ZapNax", cashPrice: null, onlinePrice: price(0.53) },
      { code: "ZAPP", description: "ZapNax Pack", cashPrice: null, onlinePrice: price(3.15) },
    ],
  },
  {
    id: "013",
    name: "Soups",
    items: [
      { code: "BEAN", description: "Beans kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BEEF", description: "Beef Kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BRON", description: "Brono Gravy", cashPrice: null, onlinePrice: price(1.05) },
      { code: "BST", description: "Bisto Gravy 125g", cashPrice: null, onlinePrice: price(1.05) },
      { code: "BSTO", description: "Bisto Gravy 250g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CAB", description: "Cabbages", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CARRT", description: "Carrots", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CHCK", description: "Chicken full", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CUC", description: "Cucumber", cashPrice: null, onlinePrice: price(0.0) },
      { code: "EGG", description: "Eggs", cashPrice: null, onlinePrice: price(0.0) },
      { code: "GARLI", description: "Garlic", cashPrice: null, onlinePrice: price(0.0) },
      { code: "GREBN", description: "Green Beans", cashPrice: null, onlinePrice: price(0.0) },
      { code: "KNOR", description: "Knorr Soup", cashPrice: null, onlinePrice: price(0.53) },
      { code: "LETT", description: "Lettuce", cashPrice: null, onlinePrice: price(0.0) },
      { code: "ONIO", description: "Onion", cashPrice: null, onlinePrice: price(0.0) },
      { code: "ORANG", description: "Orange - pocket", cashPrice: null, onlinePrice: price(0.0) },
      { code: "ROY", description: "Royco Satchet", cashPrice: null, onlinePrice: price(0.53) },
      { code: "ROYC", description: "Royco Box 12s", cashPrice: null, onlinePrice: price(0.0) },
      { code: "RYC", description: "Royco Mchuzi", cashPrice: null, onlinePrice: price(2.1) },
      { code: "SAUC", description: "Sausage kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SPIC", description: "Spice", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TOM", description: "Tomatoes kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TOPL", description: "Top Soy 90g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "USV", description: "Usavi Mix", cashPrice: null, onlinePrice: price(0.35) },
    ],
  },
  {
    id: "014",
    name: "Spices",
    items: [
      { code: "SOTHCTN", description: "Southern Coating - 200g", cashPrice: null, onlinePrice: price(1.58) },
    ],
  },
  {
    id: "015",
    name: "Spreads",
    items: [
      { code: "BLUE", description: "Blue Band", cashPrice: null, onlinePrice: price(1.05) },
      { code: "BTT", description: "Buttercup Brick 500g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BUTC", description: "ButterCup 250ml", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BUTT", description: "ButterCup tub", cashPrice: null, onlinePrice: price(2.1) },
      { code: "MAR", description: "Marmalade Jam 500g", cashPrice: null, onlinePrice: price(2.1) },
      { code: "PNUT", description: "Peanut Butter 1L", cashPrice: null, onlinePrice: price(3.15) },
      { code: "PNUTB", description: "Peanut Butter 375ml", cashPrice: null, onlinePrice: price(1.05) },
      { code: "ROMI", description: "Romi Margarine", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SNJAM", description: "SunJam 900g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SUNJ", description: "SunJam 500g", cashPrice: null, onlinePrice: price(1.58) },
      { code: "TJAM", description: "Topjam 900g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TOP", description: "Top Jam 400ml", cashPrice: null, onlinePrice: price(1.05) },
      { code: "ZMG", description: "Zimgold Marg  Tub", cashPrice: null, onlinePrice: price(0.0) },
    ],
  },
  {
    id: "016",
    name: "Starch",
    items: [
      { code: "AROMA", description: "Noddles Aroma", cashPrice: null, onlinePrice: price(1.26) },
      { code: "ASHN", description: "Ashna Rice 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "BAS", description: "Basmattii 5kg", cashPrice: null, onlinePrice: price(10.5) },
      { code: "BEL", description: "Bella Macaroni 3kg", cashPrice: null, onlinePrice: price(4.2) },
      { code: "BET", description: "BetterBuy RollerMeal 10kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "BETT", description: "BetterBuy Macaroni 3kg", cashPrice: null, onlinePrice: price(4.2) },
      { code: "BETTR", description: "BetterBuy Spagetti", cashPrice: null, onlinePrice: price(0.53) },
      { code: "BRE", description: "Bread", cashPrice: null, onlinePrice: price(1.05) },
      { code: "BTBUY", description: "BetterBuy 400g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "CAKFLR", description: "SnowFlak Cake Flour 2.5kg", cashPrice: null, onlinePrice: price(3.68) },
      { code: "CASM", description: "Noddles  casamia", cashPrice: null, onlinePrice: price(0.0) },
      { code: "CONT", description: "Continental Rice 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "COO", description: "Cookmore Rice 5kg", cashPrice: null, onlinePrice: price(5.78) },
      { code: "COOKM", description: "CookMore Rice 2kg", cashPrice: null, onlinePrice: price(2.63) },
      { code: "DON", description: "Donunt", cashPrice: null, onlinePrice: price(0.0) },
      { code: "EKN", description: "Ekono Rice white 2kg", cashPrice: null, onlinePrice: price(2.31) },
      { code: "EKO", description: "Ekono white Rice 5kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "EKON", description: "Ekono Macaron 3kg", cashPrice: null, onlinePrice: price(4.2) },
      { code: "EKONO", description: "Spagetti 400g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "EKSP01", description: "Ekono Spaghett - Box (8kg)", cashPrice: null, onlinePrice: price(0.0) },
      { code: "GOLF", description: "Noddles Golf", cashPrice: null, onlinePrice: price(1.26) },
      { code: "IDE", description: "Ideal white Rice 5kg", cashPrice: null, onlinePrice: price(5.46) },
      { code: "IDEL", description: "Ideal whie Rice 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "INDO", description: "Noddles Indomie", cashPrice: null, onlinePrice: price(1.58) },
      { code: "JAS", description: "Jasmine Rice 2kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MAC", description: "Macaroni Box", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MACR01", description: "Macaron - 400g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "MAHA", description: "Mahatma 2kg", cashPrice: null, onlinePrice: price(2.63) },
      { code: "MAHT", description: "Mahatma 5kg", cashPrice: null, onlinePrice: price(6.3) },
      { code: "MAHTMCS", description: "MAHATMA 2kg - Case", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MARA", description: "Mariana Spagetti", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MARI", description: "Mariiana 1kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "MART", description: "Martina White Rice 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "MARTIN", description: "Martina Rice 5kg", cashPrice: null, onlinePrice: price(5.46) },
      { code: "MEG", description: "Parboiled Rice 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "MEGA", description: "Mega Macaroni - 3KG", cashPrice: null, onlinePrice: price(4.2) },
      { code: "MEGAM", description: "Mega Macaroni 400g", cashPrice: null, onlinePrice: price(0.53) },
      { code: "MEGR01", description: "Mega Rice - 2kg", cashPrice: null, onlinePrice: price(2.31) },
      { code: "MEGRC", description: "Mega Rice - 5kg", cashPrice: null, onlinePrice: price(6.09) },
      { code: "MGAA", description: "Mega All Purpose 2kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "MR", description: "Mr Rice White 2kg", cashPrice: null, onlinePrice: price(2.31) },
      { code: "MRR", description: "Mr Rice white 5kg", cashPrice: null, onlinePrice: price(5.46) },
      { code: "NGW", description: "Ngwerevere", cashPrice: null, onlinePrice: price(0.0) },
      { code: "NODB", description: "Noddle Box", cashPrice: null, onlinePrice: price(10.5) },
      { code: "NODBNT", description: "Noddles Binto", cashPrice: null, onlinePrice: price(1.26) },
      { code: "NODD", description: "Noodle Kellogs/Golf Box", cashPrice: null, onlinePrice: price(12.6) },
      { code: "NODL", description: "Noddles Mega", cashPrice: null, onlinePrice: price(1.37) },
      { code: "NODPCK", description: "Noddles Kellogs", cashPrice: null, onlinePrice: price(1.68) },
      { code: "PAR", description: "Parboiled Rice 5kg", cashPrice: null, onlinePrice: price(5.46) },
      { code: "PAST", description: "Pastarelli - Macaroni 3kg", cashPrice: null, onlinePrice: price(4.2) },
      { code: "PEARL", description: "Pearlenta 10kg", cashPrice: null, onlinePrice: price(8.4) },
      { code: "PIE", description: "Pie", cashPrice: null, onlinePrice: price(0.53) },
      { code: "PLAI", description: "Plain Flour 2kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "POTA", description: "Potatoes 15kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "PRIM", description: "Primo Pasta", cashPrice: null, onlinePrice: price(0.0) },
      { code: "PRIMO", description: "Primo Fusilli 650g", cashPrice: null, onlinePrice: price(0.0) },
      { code: "RAHA", description: "Raha white Rice 2kg", cashPrice: null, onlinePrice: price(2.31) },
      { code: "RHA", description: "Raha white Rice 5kg", cashPrice: null, onlinePrice: price(5.78) },
      { code: "RLLR", description: "Roller meal Irifarm 5kg", cashPrice: null, onlinePrice: price(3.15) },
      { code: "ROLER", description: "Roller Meal 10kg", cashPrice: null, onlinePrice: price(6.3) },
      { code: "ROLLS", description: "Roller SuperLife 5kg", cashPrice: null, onlinePrice: price(2.1) },
      { code: "SAS", description: "Sasko Flour - 5kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SASKF", description: "Sasko Flour 2.5 kg", cashPrice: null, onlinePrice: price(3.15) },
      { code: "SELF", description: "Self Raising Flour 2kg", cashPrice: null, onlinePrice: price(1.89) },
      { code: "SELFR", description: "Self Raising Flour Case", cashPrice: null, onlinePrice: price(0.0) },
      { code: "SNO", description: "SnowFake SelfRaising 2.5", cashPrice: null, onlinePrice: price(3.99) },
      { code: "SUGAR", description: "Sugar Case", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TAPI", description: "Tapi Tapi 2kg", cashPrice: null, onlinePrice: price(2.63) },
      { code: "THAI", description: "Thai Rice", cashPrice: null, onlinePrice: price(2.42) },
      { code: "THAIR", description: "Thai 5kg", cashPrice: null, onlinePrice: price(0.0) },
      { code: "TLOF", description: "Tea loaf", cashPrice: null, onlinePrice: price(0.84) },
      { code: "TOPC", description: "TopChef white Rice 5kg", cashPrice: null, onlinePrice: price(5.78) },
      { code: "TOPF", description: "TopChef 2kg", cashPrice: null, onlinePrice: price(2.63) },
      { code: "WHRC", description: "White Rice Case 2kg", cashPrice: null, onlinePrice: price(0.0) },
    ],
  },
];

export type InventoryLookupEntry = InventoryItem & {
  categoryId: string;
  categoryName: string;
};

export const inventoryByCode: Record<string, InventoryLookupEntry> = inventory.reduce(
  (acc, category) => {
    category.items.forEach(item => {
      acc[item.code] = {
        ...item,
        categoryId: category.id,
        categoryName: category.name,
        availableInstore: item.availableInstore ?? item.onlinePrice !== null,
      };
    });
    return acc;
  },
  {} as Record<string, InventoryLookupEntry>,
);

export const flatInventory: InventoryLookupEntry[] = Object.values(inventoryByCode);
