import { inventoryByCode } from "@/lib/inventory";

export const categories = [
  "Fruit & Veg",
  "Butchery",
  "Grocery & Spices",
  "Baby",
  "Cleaning Products",
  "Cosmetics",
  "Toiletries",
] as const;

export type Category = typeof categories[number];

export const subCategories = [
    "None",
    "Baby",
    "Beverages",
    "Cereals",
    "Cleaning Products",
    "Cosmetics",
    "Dairy",
    "Dried",
    "Oils & Sauces",
    "Other Items",
    "Salad Dressing",
    "Seasoning",
    "Snack",
    "Soups",
    "Spices",
    "Spreads",
    "Starch",
    "Stationery",
    "Tea & Breakfast",
    "Toiletries",
    "Canned Foods"
] as const;

export type SubCategory = typeof subCategories[number];

export type Product = {
  id: number;
  name: string;
  price: number;
  oldPrice?: number;
  unit: string;
  category: Category;
  subcategory?: SubCategory;
  image: string;
  onSpecial: boolean;
};

const onlinePrice = (code: string, fallback = 0): number =>
  inventoryByCode[code]?.onlinePrice ?? fallback;

// ⬇️ ADD THIS ENTIRE BLOCK ⬇️
// This array defines the images that your other components need.
export const PlaceHolderImages = [
  { id: "hero-produce", src: "/images/hero-produce.webp" },
  { id: "gallery-2", src: "/images/gallery-2.webp" },
  { id: "gallery-4", src: "/images/gallery-4.webp" },
  { id: "product-apples", src: "/images/product-apples.webp" },
  { id: "product-carrots", src: "/images/product-carrots.webp" },
  { id: "product-broccoli", src: "/images/product-broccoli.webp" },
  { id: "product-steak", src: "/images/product-steak.webp" },
  { id: "product-sausages", src: "/images/product-sausages.webp" },
  { id: "product-chicken", src: "/images/product-chicken.webp" },
  { id: "product-bread", src: "/images/product-bread.webp" },
  { id: "product-spices", src: "/images/product-spices.webp" },
  { id: "product-eggs", src: "/images/product-eggs.webp" },
];
// ⬆️ END OF BLOCK TO ADD ⬆️


export const products: Product[] = [
  {
    id: 1,
    name: "Red Apples",
    price: 1.5,
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 2,
    name: "Fresh Carrots",
    price: 1.0,
    unit: "/bunch",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: true,
    oldPrice: 1.25,
  },
  {
    id: 3,
    name: "Broccoli",
    price: 2.0,
    unit: "/head",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 4,
    name: "Prime Rump Steak",
    price: 9.5,
    unit: "/kg",
    category: "Butchery",
    image: "product-steak",
    onSpecial: false,
  },
  {
    id: 5,
    name: "Boerewors Sausages",
    price: 7.0,
    unit: "/kg",
    category: "Butchery",
    image: "product-sausages",
    onSpecial: true,
    oldPrice: 8.5,
  },
  {
    id: 6,
    name: "Chicken Fillets",
    price: 6.5,
    unit: "/kg",
    category: "Butchery",
    image: "product-chicken",
    onSpecial: false,
  },
  {
    id: 7,
    name: "Artisanal Bread Loaf",
    price: 3.0,
    unit: "/loaf",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 8,
    name: "Mixed Spices",
    price: 2.5,
    unit: "/jar",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 9,
    name: "Farm Fresh Eggs",
    price: 2.8,
    unit: "/dozen",
    category: "Grocery & Spices",
    subcategory: "Dairy",
    image: "product-eggs",
    onSpecial: true,
    oldPrice: 3.2,
  },
  {
    id: 10,
    name: "Apples Assorted - Heads (FACP04)",
    price: onlinePrice("FACP04"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 11,
    name: "Apples Econo - 1.5kg (FACE01)",
    price: onlinePrice("FACE01"),
    unit: "/1.5kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 12,
    name: "Apples Econo - Box (FACPI)",
    price: onlinePrice("FACPI"),
    unit: "/box",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 13,
    name: "Avocado - Heads (FAMT1)",
    price: onlinePrice("FAMT1"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 14,
    name: "Bananas - kg (BN102)",
    price: onlinePrice("BN102"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 15,
    name: "Bananas Misc - kg (BANMC)",
    price: onlinePrice("BANMC"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 16,
    name: "Baobab (Powdered) - 500g (BOB)",
    price: onlinePrice("BOB"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 17,
    name: "Baobab - 500g (BOAB0001)",
    price: onlinePrice("BOAB0001"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 18,
    name: "Beetroot - Bundle (VBER01)",
    price: onlinePrice("VBER01"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 19,
    name: "Brinjals - kg (VBR06)",
    price: onlinePrice("VBR06"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 20,
    name: "Broccolli - kg (VBN09)",
    price: onlinePrice("VBN09"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 21,
    name: "Brown Rice - 1kg (BRWN)",
    price: onlinePrice("BRWN"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 22,
    name: "Brown Rice - 2kg (BROWN02)",
    price: onlinePrice("BROWN02"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 23,
    name: "Bulk - Mufushwa (Bucket) (MUFUSBULK)",
    price: onlinePrice("MUFUSBULK"),
    unit: "/bucket",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 24,
    name: "Bulk - Rapoko - Buckets (ROAST)",
    price: onlinePrice("ROAST"),
    unit: "/bucket",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 25,
    name: "Bulk - Sugar Beans (BLKSUGR01)",
    price: onlinePrice("BLKSUGR01"),
    unit: "/bulk pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 26,
    name: "Butternuts - kg (VBNO10)",
    price: onlinePrice("VBNO10"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 27,
    name: "Butternut - Punnet (VBUTT)",
    price: onlinePrice("VBUTT"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 28,
    name: "Butternut - Pocket (BUTP)",
    price: onlinePrice("BUTP"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 29,
    name: "Cabbage - Head (VCA11)",
    price: onlinePrice("VCA11"),
    unit: "/head",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 30,
    name: "Cabbages Red (VCAM)",
    price: onlinePrice("VCAM"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 31,
    name: "Carrots - Punnet (VPCP23)",
    price: onlinePrice("VPCP23"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 32,
    name: "Carrots - kg (VCP21)",
    price: onlinePrice("VCP21"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 33,
    name: "Cauliflower - kg (VCAU01)",
    price: onlinePrice("VCAU01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 34,
    name: "Chimera (NCB02)",
    price: onlinePrice("NCB02"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 35,
    name: "Covo - Bunches (DCOO1)",
    price: onlinePrice("DCOO1"),
    unit: "/bunch",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 36,
    name: "Cucumber - Big Pack (VCUC02)",
    price: onlinePrice("VCUC02"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 37,
    name: "Eggplant - kg (EG)",
    price: onlinePrice("EG"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 38,
    name: "Eggs - Each (MFS01)",
    price: onlinePrice("MFS01"),
    unit: "/each",
    category: "Grocery & Spices",
    subcategory: "Dairy",
    image: "product-eggs",
    onSpecial: false,
  },
  {
    id: 39,
    name: "Eggs - Trays (EGT)",
    price: onlinePrice("EGT"),
    unit: "/tray",
    category: "Grocery & Spices",
    subcategory: "Dairy",
    image: "product-eggs",
    onSpecial: false,
  },
  {
    id: 40,
    name: "English Cucumber (NFI01)",
    price: onlinePrice("NFI01"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 41,
    name: "garlic - kg (VGAR)",
    price: onlinePrice("VGAR"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 42,
    name: "gemsquash - kg (VGM01)",
    price: onlinePrice("VGM01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 43,
    name: "ginger - kg (VGI130)",
    price: onlinePrice("VGI130"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 44,
    name: "grapes Black - Punnets (FGR02)",
    price: onlinePrice("FGR02"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 45,
    name: "green Beans - kg (VGB33)",
    price: onlinePrice("VGB33"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 46,
    name: "green Beans - Punnet (VGB34)",
    price: onlinePrice("VGB34"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 47,
    name: "Honey - 500g (MHO1)",
    price: onlinePrice("MHO1"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 48,
    name: "Honey Pure - 500g (1st Grade) (HONP003)",
    price: onlinePrice("HONP003"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 49,
    name: "Kapenta - kg (MFK05)",
    price: onlinePrice("MFK05"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 50,
    name: "Lemon - Punnet (VLEEKB)",
    price: onlinePrice("VLEEKB"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 51,
    name: "Lemons - kg (FLEM01)",
    price: onlinePrice("FLEM01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 52,
    name: "Lettuce - Head (VLET01)",
    price: onlinePrice("VLET01"),
    unit: "/head",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 53,
    name: "Macadamia Nuts - kg (VPEP06)",
    price: onlinePrice("VPEP06"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 54,
    name: "Macadamia Nuts - Punnet (VPEP07)",
    price: onlinePrice("VPEP07"),
    unit: "/punnet",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 55,
    name: "Madora - kg (MMDR01)",
    price: onlinePrice("MMDR01"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 56,
    name: "Mango - kg (MAN)",
    price: onlinePrice("MAN"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 57,
    name: "Mango - Packs (VMAN)",
    price: onlinePrice("VMAN"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 58,
    name: "Mixed grain - 2kg (MMIXED)",
    price: onlinePrice("MMIXED"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 59,
    name: "Munyemba - 75g (MUNY002)",
    price: onlinePrice("MUNY002"),
    unit: "/75g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 60,
    name: "Munyevhe - 50g (VOK44)",
    price: onlinePrice("VOK44"),
    unit: "/50g pack",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 61,
    name: "Naartjies - Box (FNEC02)",
    price: onlinePrice("FNEC02"),
    unit: "/box",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 62,
    name: "Naartjies - Each (FNEC03)",
    price: onlinePrice("FNEC03"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 63,
    name: "Nyimo - 500g (NYOO2)",
    price: onlinePrice("NYOO2"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 64,
    name: "Okra - Punnet (VOK41)",
    price: onlinePrice("VOK41"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 65,
    name: "Onion Red (kgs) (ON-02)",
    price: 0.0,
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 66,
    name: "Onion King Bun (VEKIG)",
    price: onlinePrice("VEKIG"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 67,
    name: "Onions - kg (VOIM53)",
    price: onlinePrice("VOIM53"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 68,
    name: "Onions - Pocket (VOIL04)",
    price: onlinePrice("VOIL04"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 69,
    name: "Onions Misc - kg (VOIM03)",
    price: onlinePrice("VOIM03"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 70,
    name: "Onions Red - Bundle (VEGON)",
    price: onlinePrice("VEGON"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 71,
    name: "Oranges - Pack (FORP01)",
    price: onlinePrice("FORP01"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 72,
    name: "Oranges - Pocket (FORA43)",
    price: onlinePrice("FORA43"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 73,
    name: "Pecan Nuts - kg (VPEC02)",
    price: onlinePrice("VPEC02"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 74,
    name: "Pecanuts - Pack (VPEN01)",
    price: onlinePrice("VPEN01"),
    unit: "/pack",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 75,
    name: "Peanut Butter - 300ml (PEANT06)",
    price: onlinePrice("PEANT06"),
    unit: "/300ml",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 76,
    name: "Peanut Butter - 375ml (MPEN)",
    price: onlinePrice("MPEN"),
    unit: "/375ml",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 77,
    name: "Peanuts (Unshelled) - 75g (PEANT001)",
    price: onlinePrice("PEANT001"),
    unit: "/75g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 78,
    name: "Peanuts - kg (PEA)",
    price: onlinePrice("PEA"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 79,
    name: "Peanuts - 500g (MSPN75)",
    price: onlinePrice("MSPN75"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 80,
    name: "Pears Forelle - Each (FPF04)",
    price: onlinePrice("FPF04"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 81,
    name: "Peas Big - Punnet (VPE02)",
    price: onlinePrice("VPE02"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 82,
    name: "Pepper (green) - Punnets (VPEP66)",
    price: onlinePrice("VPEP66"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 83,
    name: "Pepper (green)- kg (VPE65)",
    price: onlinePrice("VPE65"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 84,
    name: "Pepper Red - kg (VPEPC03)",
    price: onlinePrice("VPEPC03"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 85,
    name: "Pepper Yellow (VPEPP)",
    price: onlinePrice("VPEPP"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 86,
    name: "Pine Apples - Each (FPIN02)",
    price: onlinePrice("FPIN02"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 87,
    name: "Potatoes - 5kg (VPTIM02)",
    price: onlinePrice("VPTIM02"),
    unit: "/5kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 88,
    name: "Potatoes - 7.5kg (VP271)",
    price: onlinePrice("VP271"),
    unit: "/7.5kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 89,
    name: "Potatoes - kg (VPOTL01)",
    price: onlinePrice("VPOTL01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 90,
    name: "Potatoes - Large 15kg Pocket (VPL68)",
    price: onlinePrice("VPL68"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 91,
    name: "Potatoes - 3kg Med Pack (VPOT04)",
    price: onlinePrice("VPOT04"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 92,
    name: "Raisins - Punnets (FDFRO2)",
    price: onlinePrice("FDFRO2"),
    unit: "/punnet",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 93,
    name: "Rapoko - 1kg (RAP)",
    price: onlinePrice("RAP"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 94,
    name: "Rapoko - 2kg (RPW06)",
    price: onlinePrice("RPW06"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 95,
    name: "Rapoko - 5kg (MGRO)",
    price: onlinePrice("MGRO"),
    unit: "/5kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 96,
    name: "Rapoko - kg (RAPKG)",
    price: onlinePrice("RAPKG"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 97,
    name: "Rice (White) - 1kg (RPW10)",
    price: onlinePrice("RPW10"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 98,
    name: "Rice (White) - 2kg (RPW12)",
    price: onlinePrice("RPW12"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 99,
    name: "Roundnuts - kg (MGFG01)",
    price: onlinePrice("MGFG01"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 100,
    name: "Samp - kg (SAMP001)",
    price: onlinePrice("SAMP001"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 101,
    name: "Sauce - 1L (SCE03)",
    price: onlinePrice("SCE03"),
    unit: "/1L",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 102,
    name: "Sauce - 330ml (SCE02)",
    price: onlinePrice("SCE02"),
    unit: "/330ml",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 103,
    name: "Sauce - 375ml (SAUC004)",
    price: onlinePrice("SAUC004"),
    unit: "/375ml",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 104,
    name: "Sauce BBQ - 2 Litres (SCE01)",
    price: onlinePrice("SCE01"),
    unit: "/2L",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 105,
    name: "Sauce Daddies - 375ml (SAUCDIES)",
    price: onlinePrice("SAUCDIES"),
    unit: "/375ml",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 106,
    name: "Seeds (SEDS)",
    price: onlinePrice("SEDS"),
    unit: "/unit",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 107,
    name: "Sorghum - 1kg (SORGA)",
    price: onlinePrice("SORGA"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 108,
    name: "Sorghum - kg (SORGBK)",
    price: onlinePrice("SORGBK"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 109,
    name: "Spice - 200g (SPCE003)",
    price: onlinePrice("SPCE003"),
    unit: "/200g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 110,
    name: "Spice BBQ - 500g (BLPER)",
    price: onlinePrice("BLPER"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 111,
    name: "Spices - 100g (SPC004)",
    price: onlinePrice("SPC004"),
    unit: "/100g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 112,
    name: "Spices - 60g Satchets (MSSP)",
    price: onlinePrice("MSSP"),
    unit: "/60g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 113,
    name: "Sugar Beans - 1kg (MSB12)",
    price: onlinePrice("MSB12"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 114,
    name: "Sugar Beans -Misc - kg (MSB15)",
    price: onlinePrice("MSB15"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 115,
    name: "Sugar Beans - 2kg (MSB14)",
    price: onlinePrice("MSB14"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 116,
    name: "Sugar Beans - kg (MSB16)",
    price: onlinePrice("MSB16"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 117,
    name: "Sweet Potatoes - kg (VSP82)",
    price: onlinePrice("VSP82"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 118,
    name: "Tomatoes - kg (VTO83)",
    price: onlinePrice("VTO83"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 119,
    name: "Tomatoes Misc - kg (VTOMSC)",
    price: onlinePrice("VTOMSC"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 120,
    name: "Vinegar - 750ml (VIGR750)",
    price: onlinePrice("VIGR750"),
    unit: "/750ml",
    category: "Grocery & Spices",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 121,
    name: "Wheat - 2kg (WHT)",
    price: onlinePrice("WHT"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 122,
    name: "Wheat - Buckets (WHETBK)",
    price: onlinePrice("WHETBK"),
    unit: "/bucket",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },

  {
    id: 123,
    name: "Baby & Me Cream (BABC)",
    price: onlinePrice("BABC"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-baby-and-me-cream",
    onSpecial: false,
  },
  {
    id: 124,
    name: "Epimax Cream 400g (EPX)",
    price: onlinePrice("EPX"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-epimax-cream-400g",
    onSpecial: false,
  },
  {
    id: 125,
    name: "Huggies Diapers - Pack (HUGD)",
    price: onlinePrice("HUGD"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-diapers-pack",
    onSpecial: false,
  },
  {
    id: 126,
    name: "Huggies Wipes (HUGW)",
    price: onlinePrice("HUGW"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-wipes",
    onSpecial: false,
  },
  {
    id: 127,
    name: "Johnson Jelly 325ml (JOH)",
    price: onlinePrice("JOH"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-jelly-325ml",
    onSpecial: false,
  },
  {
    id: 128,
    name: "Johnson Aqueous 350ml (JOHA)",
    price: onlinePrice("JOHA"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-aqueous-350ml",
    onSpecial: false,
  },
  {
    id: 129,
    name: "Johnson Baby soap 175g (JOHN)",
    price: onlinePrice("JOHN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-baby-soap-175g",
    onSpecial: false,
  },
  {
    id: 130,
    name: "Masters Wipes (MASTW)",
    price: onlinePrice("MASTW"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-masters-wipes",
    onSpecial: false,
  },
  {
    id: 131,
    name: "Nan 1;2;3&4 (NAN)",
    price: onlinePrice("NAN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-nan-formula",
    onSpecial: false,
  },
  {
    id: 132,
    name: "Pampers Masters Pack (PAMP)",
    price: onlinePrice("PAMP"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-pack",
    onSpecial: false,
  },
  {
    id: 133,
    name: "Pampers Masters Single (PAMPS)",
    price: onlinePrice("PAMPS"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-single",
    onSpecial: false,
  },
  {
    id: 134,
    name: "Predo  Wipes (PRED)",
    price: onlinePrice("PRED"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-predo-wipes",
    onSpecial: false,
  },
  {
    id: 135,
    name: "Purity Aqueous (PURA)",
    price: onlinePrice("PURA"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-purity-aqueous",
    onSpecial: false,
  },
  {
    id: 136,
    name: "Soft Care Pampers (SOFT)",
    price: onlinePrice("SOFT"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-pack",
    onSpecial: false,
  },
  {
    id: 137,
    name: "Sunlight soap (SUNS)",
    price: onlinePrice("SUNS"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-baby-soap-175g",
    onSpecial: false,
  },
  {
    id: 138,
    name: "Superdry - Pamper (SUPRDY)",
    price: onlinePrice("SUPRDY"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-single",
    onSpecial: false,
  },
  {
    id: 139,
    name: "Wipes (WIP)",
    price: onlinePrice("WIP"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-masters-wipes",
    onSpecial: false,
  },
  {
    id: 140,
    name: "Johnson Wipes (WIPJOHN)",
    price: onlinePrice("WIPJOHN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-wipes",
    onSpecial: false,
  },
  {
    id: 141,
    name: "Aloha Washing Pwd 2kg (ALH)",
    price: onlinePrice("ALH"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwd-2kg",
    onSpecial: false,
  },
  {
    id: 142,
    name: "Aloha Washing Pwd 1kg (ALO)",
    price: onlinePrice("ALO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwd-1kg",
    onSpecial: false,
  },
  {
    id: 143,
    name: "Aloha Dishwasher (ALOD)",
    price: onlinePrice("ALOD"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-dishwasher",
    onSpecial: false,
  },
  {
    id: 144,
    name: "Aloha Washing Pwdr 500g (ALOH)",
    price: onlinePrice("ALOH"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwdr-500g",
    onSpecial: false,
  },
  {
    id: 145,
    name: "Arpic Cleaner 750ml (ARP)",
    price: onlinePrice("ARP"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "arpic-cleaner-750ml",
    onSpecial: false,
  },
  {
    id: 146,
    name: "BigBen bar (BIG)",
    price: onlinePrice("BIG"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "bigben-bar",
    onSpecial: false,
  },
  {
    id: 147,
    name: "Boom Paste (BOM)",
    price: onlinePrice("BOM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-paste",
    onSpecial: false,
  },
  {
    id: 148,
    name: "Boom Force Cream 750ml (BOMFC)",
    price: onlinePrice("BOMFC"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-force-cream-750ml",
    onSpecial: false,
  },
  {
    id: 149,
    name: "Boom 150g (BOMM)",
    price: onlinePrice("BOMM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-150g",
    onSpecial: false,
  },
  {
    id: 150,
    name: "Boom - 1KG (BOMW)",
    price: onlinePrice("BOMW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-1kg",
    onSpecial: false,
  },
  {
    id: 151,
    name: "BoomDish washer 750ml (BOO)",
    price: onlinePrice("BOO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boomdish-washer-750ml",
    onSpecial: false,
  },
  {
    id: 152,
    name: "Boom Bleach 750ml (BOOMB)",
    price: onlinePrice("BOOMB"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-bleach-750ml",
    onSpecial: false,
  },
  {
    id: 153,
    name: "Boom Force Scouring (BOOMF)",
    price: onlinePrice("BOOMF"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-force-scouring",
    onSpecial: false,
  },
  {
    id: 154,
    name: "Boom W/P 500g (BOOMM)",
    price: onlinePrice("BOOMM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-wp-500g",
    onSpecial: false,
  },
  {
    id: 155,
    name: "Cobra 350ml (COB)",
    price: onlinePrice("COB"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "cobra-350ml",
    onSpecial: false,
  },
  {
    id: 156,
    name: "Comfort 1L (COM)",
    price: onlinePrice("COM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "comfort-1l",
    onSpecial: false,
  },
  {
    id: 157,
    name: "Dishwasher Seawave (DISW)",
    price: onlinePrice("DISW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "dishwasher-seawave",
    onSpecial: false,
  },
  {
    id: 158,
    name: "Domestos local (DOMES)",
    price: onlinePrice("DOMES"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "domestos-local",
    onSpecial: false,
  },
  {
    id: 159,
    name: "Domestos (DOMS)",
    price: onlinePrice("DOMS"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "domestos",
    onSpecial: false,
  },
  {
    id: 160,
    name: "Gik 750ml (GK)",
    price: onlinePrice("GK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "gik-750ml",
    onSpecial: false,
  },
  {
    id: 161,
    name: "Green Bar Perfection (GREE)",
    price: onlinePrice("GREE"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "green-bar-perfection",
    onSpecial: false,
  },
  {
    id: 162,
    name: "Green Bar (GRN)",
    price: onlinePrice("GRN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "green-bar",
    onSpecial: false,
  },
  {
    id: 163,
    name: "Handy Andy (HAN)",
    price: onlinePrice("HAN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "handy-andy",
    onSpecial: false,
  },
  {
    id: 164,
    name: "Harpic (HARP)",
    price: onlinePrice("HARP"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "harpic",
    onSpecial: false,
  },
  {
    id: 165,
    name: "Jik 750ml (JK)",
    price: onlinePrice("JK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "jik-750ml",
    onSpecial: false,
  },
  {
    id: 166,
    name: "Kiwi Polish 50ml (KIW)",
    price: onlinePrice("KIW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "kiwi-polish-50ml",
    onSpecial: false,
  },
  {
    id: 167,
    name: "Knock Dishwasher 750ml (KNCK)",
    price: onlinePrice("KNCK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knock-dishwasher-750ml",
    onSpecial: false,
  },
  {
    id: 168,
    name: "Knockout Can (KNO)",
    price: onlinePrice("KNO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-can",
    onSpecial: false,
  },
  {
    id: 169,
    name: "Knockout All Purpose Cleaner 500ml (KNOA)",
    price: onlinePrice("KNOA"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-all-purpose-cleaner-500ml",
    onSpecial: false,
  },
  {
    id: 170,
    name: "Knock out Satchet (KNOC)",
    price: onlinePrice("KNOC"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knock-out-satchet",
    onSpecial: false,
  },
  {
    id: 171,
    name: "Knockout Dishwasher 2L (KNOCK)",
    price: onlinePrice("KNOCK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-dishwasher-2l",
    onSpecial: false,
  },
  {
    id: 172,
    name: "Knockout Bleach (KNOCT)",
    price: onlinePrice("KNOCT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-bleach",
    onSpecial: false,
  },
  {
    id: 173,
    name: "Kiwi 100ml (KWI)",
    price: onlinePrice("KWI"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "kiwi-100ml",
    onSpecial: false,
  },
  {
    id: 174,
    name: "Maq 1kg (MAQ)",
    price: onlinePrice("MAQ"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "maq-1kg",
    onSpecial: false,
  },
  {
    id: 175,
    name: "Boom 2kg (MEGFLR)",
    price: onlinePrice("MEGFLR"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-2kg",
    onSpecial: false,
  },
  {
    id: 176,
    name: "Maq 2kg (MQ)",
    price: onlinePrice("MQ"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "maq-2kg",
    onSpecial: false,
  },
  {
    id: 177,
    name: "Nugget - 100ml (NUGET)",
    price: onlinePrice("NUGET"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "nugget-100ml",
    onSpecial: false,
  },
  {
    id: 178,
    name: "Omo Powder 2kg (OMO)",
    price: onlinePrice("OMO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "omo-powder-2kg",
    onSpecial: false,
  },
  {
    id: 179,
    name: "Pinegel 500ml (PIN)",
    price: onlinePrice("PIN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "pinegel-500ml",
    onSpecial: false,
  },
  {
    id: 180,
    name: "Pinegel 1L (PNE)",
    price: onlinePrice("PNE"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "pinegel-1l",
    onSpecial: false,
  },
  {
    id: 181,
    name: "DishWasher Seawave 2L (SEAW)",
    price: onlinePrice("SEAW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "dishwasher-seawave-2l",
    onSpecial: false,
  },
  {
    id: 182,
    name: "Sunlight Liquid (SNL)",
    price: onlinePrice("SNL"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-liquid",
    onSpecial: false,
  },
  {
    id: 183,
    name: "Star Soft - 2litre (STASFT)",
    price: onlinePrice("STASFT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "star-soft-2litre",
    onSpecial: false,
  },
  {
    id: 184,
    name: "StarSoft Refill mix (STS)",
    price: onlinePrice("STS"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "starsoft-refill-mix",
    onSpecial: false,
  },
  {
    id: 185,
    name: "Sunlight 1kg (SUNL)",
    price: onlinePrice("SUNL"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-1kg",
    onSpecial: false,
  },
  {
    id: 186,
    name: "SunLight Pwd 2kg (SUNLT)",
    price: onlinePrice("SUNLT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-pwd-2kg",
    onSpecial: false,
  },
  {
    id: 187,
    name: "Xtra Vim (VIM)",
    price: onlinePrice("VIM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "xtra-vim",
    onSpecial: false,
  },
  {
    id: 188,
    name: "Vim Can (VM)",
    price: onlinePrice("VM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "vim-can",
    onSpecial: false,
  },
  {
    id: 189,
    name: "XTRA Washing Powder (XTRA)",
    price: onlinePrice("XTRA"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "xtra-washing-powder",
    onSpecial: false,
  },
  {
    id: 190,
    name: "Addidas Spray (ADDSPRY)",
    price: onlinePrice("ADDSPRY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 191,
    name: "Axe Perfumer (AXP)",
    price: onlinePrice("AXP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 192,
    name: "Baby Crez 500ml (BAB)",
    price: onlinePrice("BAB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 193,
    name: "Baby line 500ml (BABL)",
    price: onlinePrice("BABL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 194,
    name: "Black Chick  Small 125ml (BCS)",
    price: onlinePrice("BCS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 195,
    name: "BeverlyHills Roll on (BEV)",
    price: onlinePrice("BEV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 196,
    name: "Beverly Hills Perfume (BEVP)",
    price: onlinePrice("BEVP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 197,
    name: "BlackChic Big 250ml (BLC)",
    price: onlinePrice("BLC"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 198,
    name: "Bodi doc (BOD)",
    price: onlinePrice("BOD"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 199,
    name: "Bodi doc Tissue Oil (BODD)",
    price: onlinePrice("BODD"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 200,
    name: "Boom Fabric Conditioner 2ltr (BOMO)",
    price: onlinePrice("BOMO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 201,
    name: "Clere Beautiful Cream 400ml (CBL)",
    price: onlinePrice("CBL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 202,
    name: "Clere For Men 450ml (CFM)",
    price: onlinePrice("CFM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 203,
    name: "Clere Glycerine 100ml (CLG)",
    price: onlinePrice("CLG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 204,
    name: "Clere Men lotion 400ml (CLM)",
    price: onlinePrice("CLM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 205,
    name: "Clere Glyco Glycerine 100ml (CLR)",
    price: onlinePrice("CLR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 206,
    name: "Clere Ladies Cream (CLRE)",
    price: onlinePrice("CLRE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 207,
    name: "Cosmo Foam Bath (COSMO)",
    price: onlinePrice("COSMO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 208,
    name: "Dark& Lovely (DAR)",
    price: onlinePrice("DAR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 209,
    name: "Dawn (DAW)",
    price: onlinePrice("DAW"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 210,
    name: "Dawn Cream (DAWN)",
    price: onlinePrice("DAWN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 211,
    name: "Dax 3 in 1 375mls (DAX31)",
    price: onlinePrice("DAX31"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 212,
    name: "Dax Hair Grower 250ml (DAXG)",
    price: onlinePrice("DAXG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 213,
    name: "Dax Hair Grower 125mls (DAXH)",
    price: onlinePrice("DAXH"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 214,
    name: "Dax Freez Big 250ml (DAXI)",
    price: onlinePrice("DAXI"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 215,
    name: "Dove Lotion (DOVE)",
    price: onlinePrice("DOVE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 216,
    name: "Dax Freez Small 100ml (DXA)",
    price: onlinePrice("DXA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 217,
    name: "Dax Big 3 n 1 (DXB)",
    price: onlinePrice("DXB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 218,
    name: "English Blazer (ENG)",
    price: onlinePrice("ENG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 219,
    name: "EasyWaves Pack (EWP)",
    price: onlinePrice("EWP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 220,
    name: "Exclamation Perfume (EXCLA)",
    price: onlinePrice("EXCLA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 221,
    name: "Gentel Magic lotion (GMG)",
    price: onlinePrice("GMG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 222,
    name: "Gentle Magic Cream (GML)",
    price: onlinePrice("GML"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 223,
    name: "Gentel Magic Serum (GMS)",
    price: onlinePrice("GMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 224,
    name: "Gentel Magic Soap (GNT)",
    price: onlinePrice("GNT"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 225,
    name: "Gentle Magic Oil 50ml (GNTO)",
    price: onlinePrice("GNTO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 226,
    name: "Hair Remover Cosmo 40g (HAR)",
    price: onlinePrice("HAR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 227,
    name: "Hoit Toity 90mls (HOIT)",
    price: onlinePrice("HOIT"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 228,
    name: "Hoity Toity Lotion (HOITY)",
    price: onlinePrice("HOITY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 229,
    name: "Ingrams Herbal (IGM)",
    price: onlinePrice("IGM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 230,
    name: "Ingrams Senstive 450ml (IGMS)",
    price: onlinePrice("IGMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 231,
    name: "Ingrams Moisture Plus 450ml (IMP)",
    price: onlinePrice("IMP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 232,
    name: "Ingrams men 450ml (ING)",
    price: onlinePrice("ING"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 233,
    name: "Ingrams Aloe 450ml (INGM)",
    price: onlinePrice("INGM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 234,
    name: "Ingrams tissue oi l450ml (INGMS)",
    price: onlinePrice("INGMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 235,
    name: "Ingrams Original 450mls (INGRO)",
    price: onlinePrice("INGRO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 236,
    name: "Igrams Roibos 450ml (INR)",
    price: onlinePrice("INR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 237,
    name: "Inecto Super Black75g (ISB)",
    price: onlinePrice("ISB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 238,
    name: "Isoplus Edge Control (ISOP)",
    price: onlinePrice("ISOP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 239,
    name: "Iso Plus Hair Spry 240ml (ISP)",
    price: onlinePrice("ISP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 240,
    name: "Lace Lotion (LACE)",
    price: onlinePrice("LACE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 241,
    name: "Mousse (MOUS)",
    price: onlinePrice("MOUS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 242,
    name: "Nivea Cream/Lotion 400ml (NIV)",
    price: onlinePrice("NIV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 243,
    name: "Nivea Radiant Cream 400ml (NIVA)",
    price: onlinePrice("NIVA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 244,
    name: "Nivea Spray (NIVES)",
    price: onlinePrice("NIVES"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 245,
    name: "Nivea Q10 (NVIA)",
    price: onlinePrice("NVIA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 246,
    name: "Oh So Heavenly Lotion 720ml (OHS)",
    price: onlinePrice("OHS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 247,
    name: "Oh So Heavenly - 2L (OHSHV)",
    price: onlinePrice("OHSHV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 248,
    name: "Oh  So Heavenly Lotion 1L (OHSL)",
    price: onlinePrice("OHSL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 249,
    name: "Oh SO Heavenly Cream 450ml (OHSO)",
    price: onlinePrice("OHSO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 250,
    name: "Oh So heavenly Q10 (OHSOQ)",
    price: onlinePrice("OHSOQ"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 251,
    name: "Olive Oil Spry 250ml (OLV)",
    price: onlinePrice("OLV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 252,
    name: "PlayBoy Roll on (PLA)",
    price: onlinePrice("PLA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 253,
    name: "PlayBoy Perfume (PLAY)",
    price: onlinePrice("PLAY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 254,
    name: "Roll On Shield (RLS)",
    price: onlinePrice("RLS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 255,
    name: "Roll On Addidas 50ml (ROLL)",
    price: onlinePrice("ROLL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 256,
    name: "Roll on Nivea - 50ml (ROLNIV)",
    price: onlinePrice("ROLNIV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 257,
    name: "Roll On Power House 50ml (ROP)",
    price: onlinePrice("ROP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 258,
    name: "Shower To Shower (SHOW)",
    price: onlinePrice("SHOW"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 259,
    name: "Shower to Shower Perfume (SHWR)",
    price: onlinePrice("SHWR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 260,
    name: "Skala 200g (SKA)",
    price: onlinePrice("SKA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 261,
    name: "Skala hairFood (SKAL)",
    price: onlinePrice("SKAL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 262,
    name: "Top Society (TOPS)",
    price: onlinePrice("TOPS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 263,
    name: "Vaseline 450ml (VAS)",
    price: onlinePrice("VAS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 264,
    name: "Vaseline 250ml (VASE)",
    price: onlinePrice("VASE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 265,
    name: "v (VASEL)",
    price: onlinePrice("VASEL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 266,
    name: "Vaseline lips (VASELN)",
    price: onlinePrice("VASELN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 267,
    name: "Vaseline 50ml (VASL)",
    price: onlinePrice("VASL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 268,
    name: "Vaseline Cream (VASLN)",
    price: onlinePrice("VASLN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 269,
    name: "Vaseline Lotion (VASLNL)",
    price: onlinePrice("VASLNL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 270,
    name: "Vestline Garlic - 200g (VESTGLC)",
    price: onlinePrice("VESTGLC"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 271,
    name: "Vaseline - 100ml (VSN)",
    price: onlinePrice("VSN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 272,
    name: "Angel Care Tissue (ANG)",
    price: onlinePrice("ANG"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 273,
    name: "Aquafresh - 100ml (AQFRSH)",
    price: onlinePrice("AQFRSH"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 274,
    name: "Baby Soft 18s (BABYS)",
    price: onlinePrice("BABYS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 275,
    name: "Close Up (CLO)",
    price: onlinePrice("CLO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 276,
    name: "Colgate 100ml (COL)",
    price: onlinePrice("COL"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 277,
    name: "Utra Pads (DELLP)",
    price: onlinePrice("DELLP"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 278,
    name: "Dettol Liquid (DETO)",
    price: onlinePrice("DETO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 279,
    name: "Dettol soap (DETT)",
    price: onlinePrice("DETT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 280,
    name: "Geisha (GEI)",
    price: onlinePrice("GEI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 281,
    name: "HiLife Soap (HIL)",
    price: onlinePrice("HIL"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 282,
    name: "hygienix Soap 175g (HYG)",
    price: onlinePrice("HYG"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 283,
    name: "Jade Soap (JAD)",
    price: onlinePrice("JAD"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 284,
    name: "Kotex pads 10s (KOT)",
    price: onlinePrice("KOT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 285,
    name: "Lifebouy (LIFBY)",
    price: onlinePrice("LIFBY"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 286,
    name: "Lux Soap (LUX)",
    price: onlinePrice("LUX"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 287,
    name: "Oh So Heavenly Gel (OHSOH)",
    price: onlinePrice("OHSOH"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 288,
    name: "Kotex Pant Liners (PANT)",
    price: onlinePrice("PANT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 289,
    name: "Pads Mix (PDS)",
    price: onlinePrice("PDS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 290,
    name: "Period pants (PERI)",
    price: onlinePrice("PERI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 291,
    name: "Protex Soap (PROT)",
    price: onlinePrice("PROT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 292,
    name: "Private Joy Tissue (PRVT)",
    price: onlinePrice("PRVT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 293,
    name: "Romance Soap 50g (ROM)",
    price: onlinePrice("ROM"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 294,
    name: "Tissue Single (SAT)",
    price: onlinePrice("SAT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 295,
    name: "Satiskin 2L (SATI)",
    price: onlinePrice("SATI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 296,
    name: "Satiskin 1L (SATSK)",
    price: onlinePrice("SATSK"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 297,
    name: "Sona (SON)",
    price: onlinePrice("SON"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 298,
    name: "Tissue 4s (TISS)",
    price: onlinePrice("TISS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 299,
    name: "TwinSaver Tissue (TWIN)",
    price: onlinePrice("TWIN"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 300,
    name: "TwinSaver 9s (TWINS)",
    price: onlinePrice("TWINS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 301,
    name: "Yebo Soap (YBO)",
    price: onlinePrice("YBO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
];
