import { inventoryByCode } from "@/lib/inventory";
import {
  PlaceHolderImages as PlaceholderCatalog,
  DEFAULT_PRODUCT_IMAGE_ID,
  isGenericImageId,
  slugifyImageId,
} from "@/lib/placeholder-images";

export const categories = [
  "Fruit & Veg",
  "Butchery",
  "Grocery & Spices",
  "Baby",
  "Cleaning Products",
  "Cosmetics",
  "Toiletries",
  "Beverages",
  "Cereals",
  "Dairy",
  "Dried",
  "Oils & Sauces",
  "Other Items",
  "Salad Dressing",
  "Seasoning",
] as const;

export type Category = typeof categories[number];

export const subCategories = [
    "None",
    "Baby",
    "Beverages",
    "Cereals",
    "Cleaning Products",
    "Cosmetics",
    "Dairy",
    "Dried",
    "Oils & Sauces",
    "Other Items",
    "Salad Dressing",
    "Seasoning",
    "Snack",
    "Soups",
    "Spices",
    "Spreads",
    "Starch",
    "Stationery",
    "Tea & Breakfast",
    "Toiletries",
    "Canned Foods"
] as const;

export type SubCategory = typeof subCategories[number];

export type Product = {
  id: number;
  name: string;
  price: number;
  oldPrice?: number;
  unit: string;
  category: Category;
  subcategory?: SubCategory;
  image: string;
  onSpecial: boolean;
  sku?: string;
};

const onlinePrice = (code: string, fallback = 0): number =>
  inventoryByCode[code]?.onlinePrice ?? fallback;

// ⬇️ ADD THIS ENTIRE BLOCK ⬇️
// This array defines the images that your other components need.
export const products: Product[] = [
  {
    id: 10,
    name: "Apples Assorted - Heads",
    sku: "FACP04",
    price: onlinePrice("FACP04"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 11,
    name: "Apples Econo - 1.5kg",
    sku: "FACE01",
    price: onlinePrice("FACE01"),
    unit: "/1.5kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 12,
    name: "Apples Econo - Box",
    sku: "FACPI",
    price: onlinePrice("FACPI"),
    unit: "/box",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 13,
    name: "Avocado - Heads",
    sku: "FAMT1",
    price: onlinePrice("FAMT1"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 14,
    name: "Bananas - kg",
    sku: "BN102",
    price: onlinePrice("BN102"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 15,
    name: "Bananas Misc - kg",
    sku: "BANMC",
    price: onlinePrice("BANMC"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 16,
    name: "Baobab (Powdered) - 500g",
    sku: "BOB",
    price: onlinePrice("BOB"),
    unit: "/500g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 17,
    name: "Baobab - 500g",
    sku: "BOAB0001",
    price: onlinePrice("BOAB0001"),
    unit: "/500g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 18,
    name: "Beetroot - Bundle",
    sku: "VBER01",
    price: onlinePrice("VBER01"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 19,
    name: "Brinjals - kg",
    sku: "VBR06",
    price: onlinePrice("VBR06"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 20,
    name: "Broccolli - kg",
    sku: "VBN09",
    price: onlinePrice("VBN09"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 21,
    name: "Brown Rice - 1kg",
    sku: "BRWN",
    price: onlinePrice("BRWN"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 22,
    name: "Brown Rice - 2kg",
    sku: "BROWN02",
    price: onlinePrice("BROWN02"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 23,
    name: "Bulk - Mufushwa (Bucket)",
    sku: "MUFUSBULK",
    price: onlinePrice("MUFUSBULK"),
    unit: "/bucket",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 24,
    name: "Bulk - Rapoko - Buckets",
    sku: "ROAST",
    price: onlinePrice("ROAST"),
    unit: "/bucket",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 25,
    name: "Bulk - Sugar Beans",
    sku: "BLKSUGR01",
    price: onlinePrice("BLKSUGR01"),
    unit: "/bulk pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 26,
    name: "Butternuts - kg",
    sku: "VBNO10",
    price: onlinePrice("VBNO10"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 27,
    name: "Butternut - Punnet",
    sku: "VBUTT",
    price: onlinePrice("VBUTT"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 28,
    name: "Butternut - Pocket",
    sku: "BUTP",
    price: onlinePrice("BUTP"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 29,
    name: "Cabbage - Head",
    sku: "VCA11",
    price: onlinePrice("VCA11"),
    unit: "/head",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 30,
    name: "Cabbages Red",
    sku: "VCAM",
    price: onlinePrice("VCAM"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 31,
    name: "Carrots - Punnet",
    sku: "VPCP23",
    price: onlinePrice("VPCP23"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 32,
    name: "Carrots - kg",
    sku: "VCP21",
    price: onlinePrice("VCP21"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 33,
    name: "Cauliflower - kg",
    sku: "VCAU01",
    price: onlinePrice("VCAU01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 34,
    name: "Chimera",
    sku: "NCB02",
    price: onlinePrice("NCB02"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 35,
    name: "Covo - Bunches",
    sku: "DCOO1",
    price: onlinePrice("DCOO1"),
    unit: "/bunch",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 36,
    name: "Cucumber - Big Pack",
    sku: "VCUC02",
    price: onlinePrice("VCUC02"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 37,
    name: "Eggplant - kg",
    sku: "EG",
    price: onlinePrice("EG"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 38,
    name: "Eggs - Each",
    sku: "MFS01",
    price: onlinePrice("MFS01"),
    unit: "/each",
    category: "Dairy",
    subcategory: "Dairy",
    image: "product-eggs",
    onSpecial: false,
  },
  {
    id: 39,
    name: "Eggs - Trays",
    sku: "EGT",
    price: onlinePrice("EGT"),
    unit: "/tray",
    category: "Dairy",
    subcategory: "Dairy",
    image: "product-eggs",
    onSpecial: false,
  },
  {
    id: 40,
    name: "English Cucumber",
    sku: "NFI01",
    price: onlinePrice("NFI01"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 41,
    name: "garlic - kg",
    sku: "VGAR",
    price: onlinePrice("VGAR"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 42,
    name: "gemsquash - kg",
    sku: "VGM01",
    price: onlinePrice("VGM01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 43,
    name: "ginger - kg",
    sku: "VGI130",
    price: onlinePrice("VGI130"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 44,
    name: "grapes Black - Punnets",
    sku: "FGR02",
    price: onlinePrice("FGR02"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 45,
    name: "green Beans - kg",
    sku: "VGB33",
    price: onlinePrice("VGB33"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 46,
    name: "green Beans - Punnet",
    sku: "VGB34",
    price: onlinePrice("VGB34"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 47,
    name: "Honey - 500g",
    sku: "MHO1",
    price: onlinePrice("MHO1"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 48,
    name: "Honey Pure - 500g (1st Grade)",
    sku: "HONP003",
    price: onlinePrice("HONP003"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 49,
    name: "Kapenta - kg",
    sku: "MFK05",
    price: onlinePrice("MFK05"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 50,
    name: "Lemon - Punnet",
    sku: "VLEEKB",
    price: onlinePrice("VLEEKB"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 51,
    name: "Lemons - kg",
    sku: "FLEM01",
    price: onlinePrice("FLEM01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 52,
    name: "Lettuce - Head",
    sku: "VLET01",
    price: onlinePrice("VLET01"),
    unit: "/head",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 53,
    name: "Macadamia Nuts - kg",
    sku: "VPEP06",
    price: onlinePrice("VPEP06"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 54,
    name: "Macadamia Nuts - Punnet",
    sku: "VPEP07",
    price: onlinePrice("VPEP07"),
    unit: "/punnet",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 55,
    name: "Madora - kg",
    sku: "MMDR01",
    price: onlinePrice("MMDR01"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 56,
    name: "Mango - kg",
    sku: "MAN",
    price: onlinePrice("MAN"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 57,
    name: "Mango - Packs",
    sku: "VMAN",
    price: onlinePrice("VMAN"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 58,
    name: "Mixed grain - 2kg",
    sku: "MMIXED",
    price: onlinePrice("MMIXED"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 59,
    name: "Munyemba - 75g",
    sku: "MUNY002",
    price: onlinePrice("MUNY002"),
    unit: "/75g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 60,
    name: "Munyevhe - 50g",
    sku: "VOK44",
    price: onlinePrice("VOK44"),
    unit: "/50g pack",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 61,
    name: "Naartjies - Box",
    sku: "FNEC02",
    price: onlinePrice("FNEC02"),
    unit: "/box",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 62,
    name: "Naartjies - Each",
    sku: "FNEC03",
    price: onlinePrice("FNEC03"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 63,
    name: "Nyimo - 500g",
    sku: "NYOO2",
    price: onlinePrice("NYOO2"),
    unit: "/500g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 64,
    name: "Okra - Punnet",
    sku: "VOK41",
    price: onlinePrice("VOK41"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 65,
    name: "Onion Red (kgs)",
    sku: "ON-02",
    price: onlinePrice("ON-02"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 66,
    name: "Onion King Bun",
    sku: "VEKIG",
    price: onlinePrice("VEKIG"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 67,
    name: "Onions - kg",
    sku: "VOIM53",
    price: onlinePrice("VOIM53"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 68,
    name: "Onions - Pocket",
    sku: "VOIL04",
    price: onlinePrice("VOIL04"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 69,
    name: "Onions Misc - kg",
    sku: "VOIM03",
    price: onlinePrice("VOIM03"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 70,
    name: "Onions Red - Bundle",
    sku: "VEGON",
    price: onlinePrice("VEGON"),
    unit: "/bundle",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 71,
    name: "Oranges - Pack",
    sku: "FORP01",
    price: onlinePrice("FORP01"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 72,
    name: "Oranges - Pocket",
    sku: "FORA43",
    price: onlinePrice("FORA43"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 73,
    name: "Pecan Nuts - kg",
    sku: "VPEC02",
    price: onlinePrice("VPEC02"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 74,
    name: "Pecanuts - Pack",
    sku: "VPEN01",
    price: onlinePrice("VPEN01"),
    unit: "/pack",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 75,
    name: "Peanut Butter - 300ml",
    sku: "PEANT06",
    price: onlinePrice("PEANT06"),
    unit: "/300ml",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 76,
    name: "Peanut Butter - 375ml",
    sku: "MPEN",
    price: onlinePrice("MPEN"),
    unit: "/375ml",
    category: "Grocery & Spices",
    subcategory: "Spreads",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 77,
    name: "Peanuts (Unshelled) - 75g",
    sku: "PEANT001",
    price: onlinePrice("PEANT001"),
    unit: "/75g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 78,
    name: "Peanuts - kg",
    sku: "PEA",
    price: onlinePrice("PEA"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 79,
    name: "Peanuts - 500g",
    sku: "MSPN75",
    price: onlinePrice("MSPN75"),
    unit: "/500g pack",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 80,
    name: "Pears Forelle - Each",
    sku: "FPF04",
    price: onlinePrice("FPF04"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 81,
    name: "Peas Big - Punnet",
    sku: "VPE02",
    price: onlinePrice("VPE02"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 82,
    name: "Pepper (green) - Punnets",
    sku: "VPEP66",
    price: onlinePrice("VPEP66"),
    unit: "/punnet",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 83,
    name: "Pepper (green)- kg",
    sku: "VPE65",
    price: onlinePrice("VPE65"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 84,
    name: "Pepper Red - kg",
    sku: "VPEPC03",
    price: onlinePrice("VPEPC03"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 85,
    name: "Pepper Yellow",
    sku: "VPEPP",
    price: onlinePrice("VPEPP"),
    unit: "/unit",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 86,
    name: "Pine Apples - Each",
    sku: "FPIN02",
    price: onlinePrice("FPIN02"),
    unit: "/each",
    category: "Fruit & Veg",
    image: "product-apples",
    onSpecial: false,
  },
  {
    id: 87,
    name: "Potatoes - 5kg",
    sku: "VPTIM02",
    price: onlinePrice("VPTIM02"),
    unit: "/5kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 88,
    name: "Potatoes - 7.5kg",
    sku: "VP271",
    price: onlinePrice("VP271"),
    unit: "/7.5kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 89,
    name: "Potatoes - kg",
    sku: "VPOTL01",
    price: onlinePrice("VPOTL01"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 90,
    name: "Potatoes - Large 15kg Pocket",
    sku: "VPL68",
    price: onlinePrice("VPL68"),
    unit: "/pocket",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 91,
    name: "Potatoes - 3kg Med Pack",
    sku: "VPOT04",
    price: onlinePrice("VPOT04"),
    unit: "/pack",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 92,
    name: "Raisins - Punnets",
    sku: "FDFRO2",
    price: onlinePrice("FDFRO2"),
    unit: "/punnet",
    category: "Grocery & Spices",
    subcategory: "Snack",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 93,
    name: "Rapoko - 1kg",
    sku: "RAP",
    price: onlinePrice("RAP"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 94,
    name: "Rapoko - 2kg",
    sku: "RPW06",
    price: onlinePrice("RPW06"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 95,
    name: "Rapoko - 5kg",
    sku: "MGRO",
    price: onlinePrice("MGRO"),
    unit: "/5kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 96,
    name: "Rapoko - kg",
    sku: "RAPKG",
    price: onlinePrice("RAPKG"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 97,
    name: "Rice (White) - 1kg",
    sku: "RPW10",
    price: onlinePrice("RPW10"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 98,
    name: "Rice (White) - 2kg",
    sku: "RPW12",
    price: onlinePrice("RPW12"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 99,
    name: "Roundnuts - kg",
    sku: "MGFG01",
    price: onlinePrice("MGFG01"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 100,
    name: "Samp - kg",
    sku: "SAMP001",
    price: onlinePrice("SAMP001"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 101,
    name: "Sauce - 1L",
    sku: "SCE03",
    price: onlinePrice("SCE03"),
    unit: "/1L",
    category: "Salad Dressing",
    subcategory: "Salad Dressing",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 102,
    name: "Sauce - 330ml",
    sku: "SCE02",
    price: onlinePrice("SCE02"),
    unit: "/330ml",
    category: "Oils & Sauces",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 103,
    name: "Sauce - 375ml",
    sku: "SAUC004",
    price: onlinePrice("SAUC004"),
    unit: "/375ml",
    category: "Oils & Sauces",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 104,
    name: "Sauce BBQ - 2 Litres",
    sku: "SCE01",
    price: onlinePrice("SCE01"),
    unit: "/2L",
    category: "Oils & Sauces",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 105,
    name: "Sauce Daddies - 375ml",
    sku: "SAUCDIES",
    price: onlinePrice("SAUCDIES"),
    unit: "/375ml",
    category: "Salad Dressing",
    subcategory: "Salad Dressing",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 106,
    name: "Seeds",
    sku: "SEDS",
    price: onlinePrice("SEDS"),
    unit: "/unit",
    category: "Dried",
    subcategory: "Dried",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 107,
    name: "Sorghum - 1kg",
    sku: "SORGA",
    price: onlinePrice("SORGA"),
    unit: "/1kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 108,
    name: "Sorghum - kg",
    sku: "SORGBK",
    price: onlinePrice("SORGBK"),
    unit: "/kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 109,
    name: "Spice - 200g",
    sku: "SPCE003",
    price: onlinePrice("SPCE003"),
    unit: "/200g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 110,
    name: "Spice BBQ - 500g",
    sku: "BLPER",
    price: onlinePrice("BLPER"),
    unit: "/500g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 111,
    name: "Spices - 100g",
    sku: "SPC004",
    price: onlinePrice("SPC004"),
    unit: "/100g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 112,
    name: "Spices - 60g Satchets",
    sku: "MSSP",
    price: onlinePrice("MSSP"),
    unit: "/60g pack",
    category: "Grocery & Spices",
    subcategory: "Spices",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 113,
    name: "Sugar Beans - 1kg",
    sku: "MSB12",
    price: onlinePrice("MSB12"),
    unit: "/1kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 114,
    name: "Sugar Beans -Misc - kg",
    sku: "MSB15",
    price: onlinePrice("MSB15"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 115,
    name: "Sugar Beans - 2kg",
    sku: "MSB14",
    price: onlinePrice("MSB14"),
    unit: "/2kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 116,
    name: "Sugar Beans - kg",
    sku: "MSB16",
    price: onlinePrice("MSB16"),
    unit: "/kg",
    category: "Dried",
    subcategory: "Dried",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 117,
    name: "Sweet Potatoes - kg",
    sku: "VSP82",
    price: onlinePrice("VSP82"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-carrots",
    onSpecial: false,
  },
  {
    id: 118,
    name: "Tomatoes - kg",
    sku: "VTO83",
    price: onlinePrice("VTO83"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 119,
    name: "Tomatoes Misc - kg",
    sku: "VTOMSC",
    price: onlinePrice("VTOMSC"),
    unit: "/kg",
    category: "Fruit & Veg",
    image: "product-broccoli",
    onSpecial: false,
  },
  {
    id: 120,
    name: "Vinegar - 750ml",
    sku: "VIGR750",
    price: onlinePrice("VIGR750"),
    unit: "/750ml",
    category: "Oils & Sauces",
    subcategory: "Oils & Sauces",
    image: "product-spices",
    onSpecial: false,
  },
  {
    id: 121,
    name: "Wheat - 2kg",
    sku: "WHT",
    price: onlinePrice("WHT"),
    unit: "/2kg",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },
  {
    id: 122,
    name: "Wheat - Buckets",
    sku: "WHETBK",
    price: onlinePrice("WHETBK"),
    unit: "/bucket",
    category: "Grocery & Spices",
    subcategory: "Starch",
    image: "product-bread",
    onSpecial: false,
  },

  {
    id: 123,
    name: "Baby & Me Cream",
    sku: "BABC",
    price: onlinePrice("BABC"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-baby-and-me-cream",
    onSpecial: false,
  },
  {
    id: 124,
    name: "Epimax Cream 400g",
    sku: "EPX",
    price: onlinePrice("EPX"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-epimax-cream-400g",
    onSpecial: false,
  },
  {
    id: 125,
    name: "Huggies Diapers - Pack",
    sku: "HUGD",
    price: onlinePrice("HUGD"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-diapers-pack",
    onSpecial: false,
  },
  {
    id: 126,
    name: "Huggies Wipes",
    sku: "HUGW",
    price: onlinePrice("HUGW"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-wipes",
    onSpecial: false,
  },
  {
    id: 127,
    name: "Johnson Jelly 325ml",
    sku: "JOH",
    price: onlinePrice("JOH"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-jelly-325ml",
    onSpecial: false,
  },
  {
    id: 128,
    name: "Johnson Aqueous 350ml",
    sku: "JOHA",
    price: onlinePrice("JOHA"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-aqueous-350ml",
    onSpecial: false,
  },
  {
    id: 129,
    name: "Johnson Baby soap 175g",
    sku: "JOHN",
    price: onlinePrice("JOHN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-baby-soap-175g",
    onSpecial: false,
  },
  {
    id: 130,
    name: "Masters Wipes",
    sku: "MASTW",
    price: onlinePrice("MASTW"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-masters-wipes",
    onSpecial: false,
  },
  {
    id: 131,
    name: "Nan 1;2;3&4",
    sku: "NAN",
    price: onlinePrice("NAN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-nan-formula",
    onSpecial: false,
  },
  {
    id: 132,
    name: "Pampers Masters Pack",
    sku: "PAMP",
    price: onlinePrice("PAMP"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-pack",
    onSpecial: false,
  },
  {
    id: 133,
    name: "Pampers Masters Single",
    sku: "PAMPS",
    price: onlinePrice("PAMPS"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-single",
    onSpecial: false,
  },
  {
    id: 134,
    name: "Predo  Wipes",
    sku: "PRED",
    price: onlinePrice("PRED"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-predo-wipes",
    onSpecial: false,
  },
  {
    id: 135,
    name: "Purity Aqueous",
    sku: "PURA",
    price: onlinePrice("PURA"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-purity-aqueous",
    onSpecial: false,
  },
  {
    id: 136,
    name: "Soft Care Pampers",
    sku: "SOFT",
    price: onlinePrice("SOFT"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-pack",
    onSpecial: false,
  },
  {
    id: 137,
    name: "Sunlight soap",
    sku: "SUNS",
    price: onlinePrice("SUNS"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-johnson-baby-soap-175g",
    onSpecial: false,
  },
  {
    id: 138,
    name: "Superdry - Pamper",
    sku: "SUPRDY",
    price: onlinePrice("SUPRDY"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-pampers-masters-single",
    onSpecial: false,
  },
  {
    id: 139,
    name: "Wipes",
    sku: "WIP",
    price: onlinePrice("WIP"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-masters-wipes",
    onSpecial: false,
  },
  {
    id: 140,
    name: "Johnson Wipes",
    sku: "WIPJOHN",
    price: onlinePrice("WIPJOHN"),
    unit: "/item",
    category: "Baby",
    subcategory: "Baby",
    image: "product-huggies-wipes",
    onSpecial: false,
  },
  {
    id: 141,
    name: "Aloha Washing Pwd 2kg",
    sku: "ALH",
    price: onlinePrice("ALH"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwd-2kg",
    onSpecial: false,
  },
  {
    id: 142,
    name: "Aloha Washing Pwd 1kg",
    sku: "ALO",
    price: onlinePrice("ALO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwd-1kg",
    onSpecial: false,
  },
  {
    id: 143,
    name: "Aloha Dishwasher",
    sku: "ALOD",
    price: onlinePrice("ALOD"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-dishwasher",
    onSpecial: false,
  },
  {
    id: 144,
    name: "Aloha Washing Pwdr 500g",
    sku: "ALOH",
    price: onlinePrice("ALOH"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "aloha-washing-pwdr-500g",
    onSpecial: false,
  },
  {
    id: 145,
    name: "Arpic Cleaner 750ml",
    sku: "ARP",
    price: onlinePrice("ARP"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "arpic-cleaner-750ml",
    onSpecial: false,
  },
  {
    id: 146,
    name: "BigBen bar",
    sku: "BIG",
    price: onlinePrice("BIG"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "bigben-bar",
    onSpecial: false,
  },
  {
    id: 147,
    name: "Boom Paste",
    sku: "BOM",
    price: onlinePrice("BOM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-paste",
    onSpecial: false,
  },
  {
    id: 148,
    name: "Boom Force Cream 750ml",
    sku: "BOMFC",
    price: onlinePrice("BOMFC"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-force-cream-750ml",
    onSpecial: false,
  },
  {
    id: 149,
    name: "Boom 150g",
    sku: "BOMM",
    price: onlinePrice("BOMM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-150g",
    onSpecial: false,
  },
  {
    id: 150,
    name: "Boom - 1KG",
    sku: "BOMW",
    price: onlinePrice("BOMW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-1kg",
    onSpecial: false,
  },
  {
    id: 151,
    name: "BoomDish washer 750ml",
    sku: "BOO",
    price: onlinePrice("BOO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boomdish-washer-750ml",
    onSpecial: false,
  },
  {
    id: 152,
    name: "Boom Bleach 750ml",
    sku: "BOOMB",
    price: onlinePrice("BOOMB"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-bleach-750ml",
    onSpecial: false,
  },
  {
    id: 153,
    name: "Boom Force Scouring",
    sku: "BOOMF",
    price: onlinePrice("BOOMF"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-force-scouring",
    onSpecial: false,
  },
  {
    id: 154,
    name: "Boom W/P 500g",
    sku: "BOOMM",
    price: onlinePrice("BOOMM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-wp-500g",
    onSpecial: false,
  },
  {
    id: 155,
    name: "Cobra 350ml",
    sku: "COB",
    price: onlinePrice("COB"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "cobra-350ml",
    onSpecial: false,
  },
  {
    id: 156,
    name: "Comfort 1L",
    sku: "COM",
    price: onlinePrice("COM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "comfort-1l",
    onSpecial: false,
  },
  {
    id: 157,
    name: "Dishwasher Seawave",
    sku: "DISW",
    price: onlinePrice("DISW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "dishwasher-seawave",
    onSpecial: false,
  },
  {
    id: 158,
    name: "Domestos local",
    sku: "DOMES",
    price: onlinePrice("DOMES"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "domestos-local",
    onSpecial: false,
  },
  {
    id: 159,
    name: "Domestos",
    sku: "DOMS",
    price: onlinePrice("DOMS"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "domestos",
    onSpecial: false,
  },
  {
    id: 160,
    name: "Gik 750ml",
    sku: "GK",
    price: onlinePrice("GK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "gik-750ml",
    onSpecial: false,
  },
  {
    id: 161,
    name: "Green Bar Perfection",
    sku: "GREE",
    price: onlinePrice("GREE"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "green-bar-perfection",
    onSpecial: false,
  },
  {
    id: 162,
    name: "Green Bar",
    sku: "GRN",
    price: onlinePrice("GRN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "green-bar",
    onSpecial: false,
  },
  {
    id: 163,
    name: "Handy Andy",
    sku: "HAN",
    price: onlinePrice("HAN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "handy-andy",
    onSpecial: false,
  },
  {
    id: 164,
    name: "Harpic",
    sku: "HARP",
    price: onlinePrice("HARP"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "harpic",
    onSpecial: false,
  },
  {
    id: 165,
    name: "Jik 750ml",
    sku: "JK",
    price: onlinePrice("JK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "jik-750ml",
    onSpecial: false,
  },
  {
    id: 166,
    name: "Kiwi Polish 50ml",
    sku: "KIW",
    price: onlinePrice("KIW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "kiwi-polish-50ml",
    onSpecial: false,
  },
  {
    id: 167,
    name: "Knock Dishwasher 750ml",
    sku: "KNCK",
    price: onlinePrice("KNCK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knock-dishwasher-750ml",
    onSpecial: false,
  },
  {
    id: 168,
    name: "Knockout Can",
    sku: "KNO",
    price: onlinePrice("KNO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-can",
    onSpecial: false,
  },
  {
    id: 169,
    name: "Knockout All Purpose Cleaner 500ml",
    sku: "KNOA",
    price: onlinePrice("KNOA"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-all-purpose-cleaner-500ml",
    onSpecial: false,
  },
  {
    id: 170,
    name: "Knock out Satchet",
    sku: "KNOC",
    price: onlinePrice("KNOC"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knock-out-satchet",
    onSpecial: false,
  },
  {
    id: 171,
    name: "Knockout Dishwasher 2L",
    sku: "KNOCK",
    price: onlinePrice("KNOCK"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-dishwasher-2l",
    onSpecial: false,
  },
  {
    id: 172,
    name: "Knockout Bleach",
    sku: "KNOCT",
    price: onlinePrice("KNOCT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "knockout-bleach",
    onSpecial: false,
  },
  {
    id: 173,
    name: "Kiwi 100ml",
    sku: "KWI",
    price: onlinePrice("KWI"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "kiwi-100ml",
    onSpecial: false,
  },
  {
    id: 174,
    name: "Maq 1kg",
    sku: "MAQ",
    price: onlinePrice("MAQ"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "maq-1kg",
    onSpecial: false,
  },
  {
    id: 175,
    name: "Boom 2kg",
    sku: "MEGFLR",
    price: onlinePrice("MEGFLR"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "boom-2kg",
    onSpecial: false,
  },
  {
    id: 176,
    name: "Maq 2kg",
    sku: "MQ",
    price: onlinePrice("MQ"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "maq-2kg",
    onSpecial: false,
  },
  {
    id: 177,
    name: "Nugget - 100ml",
    sku: "NUGET",
    price: onlinePrice("NUGET"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "nugget-100ml",
    onSpecial: false,
  },
  {
    id: 178,
    name: "Omo Powder 2kg",
    sku: "OMO",
    price: onlinePrice("OMO"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "omo-powder-2kg",
    onSpecial: false,
  },
  {
    id: 179,
    name: "Pinegel 500ml",
    sku: "PIN",
    price: onlinePrice("PIN"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "pinegel-500ml",
    onSpecial: false,
  },
  {
    id: 180,
    name: "Pinegel 1L",
    sku: "PNE",
    price: onlinePrice("PNE"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "pinegel-1l",
    onSpecial: false,
  },
  {
    id: 181,
    name: "DishWasher Seawave 2L",
    sku: "SEAW",
    price: onlinePrice("SEAW"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "dishwasher-seawave-2l",
    onSpecial: false,
  },
  {
    id: 182,
    name: "Sunlight Liquid",
    sku: "SNL",
    price: onlinePrice("SNL"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-liquid",
    onSpecial: false,
  },
  {
    id: 183,
    name: "Star Soft - 2litre",
    sku: "STASFT",
    price: onlinePrice("STASFT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "star-soft-2litre",
    onSpecial: false,
  },
  {
    id: 184,
    name: "StarSoft Refill mix",
    sku: "STS",
    price: onlinePrice("STS"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "starsoft-refill-mix",
    onSpecial: false,
  },
  {
    id: 185,
    name: "Sunlight 1kg",
    sku: "SUNL",
    price: onlinePrice("SUNL"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-1kg",
    onSpecial: false,
  },
  {
    id: 186,
    name: "SunLight Pwd 2kg",
    sku: "SUNLT",
    price: onlinePrice("SUNLT"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "sunlight-pwd-2kg",
    onSpecial: false,
  },
  {
    id: 187,
    name: "Xtra Vim",
    sku: "VIM",
    price: onlinePrice("VIM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "xtra-vim",
    onSpecial: false,
  },
  {
    id: 188,
    name: "Vim Can",
    sku: "VM",
    price: onlinePrice("VM"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "vim-can",
    onSpecial: false,
  },
  {
    id: 189,
    name: "XTRA Washing Powder",
    sku: "XTRA",
    price: onlinePrice("XTRA"),
    unit: "/item",
    category: "Cleaning Products",
    subcategory: "Cleaning Products",
    image: "xtra-washing-powder",
    onSpecial: false,
  },
  {
    id: 190,
    name: "Addidas Spray",
    sku: "ADDSPRY",
    price: onlinePrice("ADDSPRY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "addidas-spray",
    onSpecial: false,
  },
  {
    id: 191,
    name: "Axe Perfumer",
    sku: "AXP",
    price: onlinePrice("AXP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "axe-perfume",
    onSpecial: false,
  },
  {
    id: 192,
    name: "Baby Crez 500ml",
    sku: "BAB",
    price: onlinePrice("BAB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "baby-crez-500ml",
    onSpecial: false,
  },
  {
    id: 193,
    name: "Baby line 500ml",
    sku: "BABL",
    price: onlinePrice("BABL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "baby-line-500ml",
    onSpecial: false,
  },
  {
    id: 194,
    name: "Black Chick  Small 125ml",
    sku: "BCS",
    price: onlinePrice("BCS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "black-chick-small-125ml",
    onSpecial: false,
  },
  {
    id: 195,
    name: "BeverlyHills Roll on",
    sku: "BEV",
    price: onlinePrice("BEV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "beverlyhills-roll-on",
    onSpecial: false,
  },
  {
    id: 196,
    name: "Beverly Hills Perfume",
    sku: "BEVP",
    price: onlinePrice("BEVP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "beverly-hills-perfume",
    onSpecial: false,
  },
  {
    id: 197,
    name: "BlackChic Big 250ml",
    sku: "BLC",
    price: onlinePrice("BLC"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "blackchic-big-250ml",
    onSpecial: false,
  },
  {
    id: 198,
    name: "Bodi doc",
    sku: "BOD",
    price: onlinePrice("BOD"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "bodi-doc",
    onSpecial: false,
  },
  {
    id: 199,
    name: "Bodi doc Tissue Oil",
    sku: "BODD",
    price: onlinePrice("BODD"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "bodi-doc-tissue-oil",
    onSpecial: false,
  },
  {
    id: 200,
    name: "Boom Fabric Conditioner 2ltr",
    sku: "BOMO",
    price: onlinePrice("BOMO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "boom-fabric-conditioner-2ltr",
    onSpecial: false,
  },
  {
    id: 201,
    name: "Clere Beautiful Cream 400ml",
    sku: "CBL",
    price: onlinePrice("CBL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-beautiful-cream-400ml",
    onSpecial: false,
  },
  {
    id: 202,
    name: "Clere For Men 450ml",
    sku: "CFM",
    price: onlinePrice("CFM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-for-men-450ml",
    onSpecial: false,
  },
  {
    id: 203,
    name: "Clere Glycerine 100ml",
    sku: "CLG",
    price: onlinePrice("CLG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-glycerine-100ml",
    onSpecial: false,
  },
  {
    id: 204,
    name: "Clere Men lotion 400ml",
    sku: "CLM",
    price: onlinePrice("CLM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-men-lotion-400ml",
    onSpecial: false,
  },
  {
    id: 205,
    name: "Clere Glyco Glycerine 100ml",
    sku: "CLR",
    price: onlinePrice("CLR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-glyco-glycerine-100ml",
    onSpecial: false,
  },
  {
    id: 206,
    name: "Clere Ladies Cream",
    sku: "CLRE",
    price: onlinePrice("CLRE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "clere-ladies-cream",
    onSpecial: false,
  },
  {
    id: 207,
    name: "Cosmo Foam Bath",
    sku: "COSMO",
    price: onlinePrice("COSMO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "cosmo-foam-bath",
    onSpecial: false,
  },
  {
    id: 208,
    name: "Dark& Lovely",
    sku: "DAR",
    price: onlinePrice("DAR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dark-and-lovely",
    onSpecial: false,
  },
  {
    id: 209,
    name: "Dawn",
    sku: "DAW",
    price: onlinePrice("DAW"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dawn",
    onSpecial: false,
  },
  {
    id: 210,
    name: "Dawn Cream",
    sku: "DAWN",
    price: onlinePrice("DAWN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dawn-cream",
    onSpecial: false,
  },
  {
    id: 211,
    name: "Dax 3 in 1 375mls",
    sku: "DAX31",
    price: onlinePrice("DAX31"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dax-3-in-1-375mls",
    onSpecial: false,
  },
  {
    id: 212,
    name: "Dax Hair Grower 250ml",
    sku: "DAXG",
    price: onlinePrice("DAXG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dax-hair-grower-250ml",
    onSpecial: false,
  },
  {
    id: 213,
    name: "Dax Hair Grower 125mls",
    sku: "DAXH",
    price: onlinePrice("DAXH"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 214,
    name: "Dax Freez Big 250ml",
    sku: "DAXI",
    price: onlinePrice("DAXI"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dax-freez-big-250ml",
    onSpecial: false,
  },
  {
    id: 215,
    name: "Dove Lotion",
    sku: "DOVE",
    price: onlinePrice("DOVE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dove-lotion",
    onSpecial: false,
  },
  {
    id: 216,
    name: "Dax Freez Small 100ml",
    sku: "DXA",
    price: onlinePrice("DXA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dax-freez-small-100ml",
    onSpecial: false,
  },
  {
    id: 217,
    name: "Dax Big 3 n 1",
    sku: "DXB",
    price: onlinePrice("DXB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "dax-big-3-n-1",
    onSpecial: false,
  },
  {
    id: 218,
    name: "English Blazer",
    sku: "ENG",
    price: onlinePrice("ENG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "english-blazer",
    onSpecial: false,
  },
  {
    id: 219,
    name: "EasyWaves Pack",
    sku: "EWP",
    price: onlinePrice("EWP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "easywaves-pack",
    onSpecial: false,
  },
  {
    id: 220,
    name: "Exclamation Perfume",
    sku: "EXCLA",
    price: onlinePrice("EXCLA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "exclamation-perfume",
    onSpecial: false,
  },
  {
    id: 221,
    name: "Gentel Magic lotion",
    sku: "GMG",
    price: onlinePrice("GMG"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "gentel-magic-lotion",
    onSpecial: false,
  },
  {
    id: 222,
    name: "Gentle Magic Cream",
    sku: "GML",
    price: onlinePrice("GML"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "gentle-magic-cream",
    onSpecial: false,
  },
  {
    id: 223,
    name: "Gentel Magic Serum",
    sku: "GMS",
    price: onlinePrice("GMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "gentel-magic-serum",
    onSpecial: false,
  },
  {
    id: 224,
    name: "Gentel Magic Soap",
    sku: "GNT",
    price: onlinePrice("GNT"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "gentel-magic-soap",
    onSpecial: false,
  },
  {
    id: 225,
    name: "Gentle Magic Oil 50ml",
    sku: "GNTO",
    price: onlinePrice("GNTO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "gentle-magic-oil-50ml",
    onSpecial: false,
  },
  {
    id: 226,
    name: "Hair Remover Cosmo 40g",
    sku: "HAR",
    price: onlinePrice("HAR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hair-remover-cosmo-40g",
    onSpecial: false,
  },
  {
    id: 227,
    name: "Hoit Toity 90mls",
    sku: "HOIT",
    price: onlinePrice("HOIT"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hoit-toity-90mls",
    onSpecial: false,
  },
  {
    id: 228,
    name: "Hoity Toity Lotion",
    sku: "HOITY",
    price: onlinePrice("HOITY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hoity-toity-lotion",
    onSpecial: false,
  },
  {
    id: 229,
    name: "Ingrams Herbal",
    sku: "IGM",
    price: onlinePrice("IGM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-herbal",
    onSpecial: false,
  },
  {
    id: 230,
    name: "Ingrams Senstive 450ml",
    sku: "IGMS",
    price: onlinePrice("IGMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-senstive-450ml",
    onSpecial: false,
  },
  {
    id: 231,
    name: "Ingrams Moisture Plus 450ml",
    sku: "IMP",
    price: onlinePrice("IMP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-moisture-plus-450ml",
    onSpecial: false,
  },
  {
    id: 232,
    name: "Ingrams men 450ml",
    sku: "ING",
    price: onlinePrice("ING"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-men-450ml",
    onSpecial: false,
  },
  {
    id: 233,
    name: "Ingrams Aloe 450ml",
    sku: "INGM",
    price: onlinePrice("INGM"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-aloe-450ml",
    onSpecial: false,
  },
  {
    id: 234,
    name: "Ingrams tissue oi l450ml",
    sku: "INGMS",
    price: onlinePrice("INGMS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-tissue-oi-l450ml",
    onSpecial: false,
  },
  {
    id: 235,
    name: "Ingrams Original 450mls",
    sku: "INGRO",
    price: onlinePrice("INGRO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "ingrams-original-450mls",
    onSpecial: false,
  },
  {
    id: 236,
    name: "Igrams Roibos 450ml",
    sku: "INR",
    price: onlinePrice("INR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "igrams-roibos-450ml",
    onSpecial: false,
  },
  {
    id: 237,
    name: "Inecto Super Black75g",
    sku: "ISB",
    price: onlinePrice("ISB"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "inecto-super-black75g",
    onSpecial: false,
  },
  {
    id: 238,
    name: "Isoplus Edge Control",
    sku: "ISOP",
    price: onlinePrice("ISOP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "isoplus-edge-control",
    onSpecial: false,
  },
  {
    id: 239,
    name: "Iso Plus Hair Spry 240ml",
    sku: "ISP",
    price: onlinePrice("ISP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "iso-plus-hair-spry-240ml",
    onSpecial: false,
  },
  {
    id: 240,
    name: "Lace Lotion",
    sku: "LACE",
    price: onlinePrice("LACE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "lace-lotion",
    onSpecial: false,
  },
  {
    id: 241,
    name: "Mousse",
    sku: "MOUS",
    price: onlinePrice("MOUS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "mousse",
    onSpecial: false,
  },
  {
    id: 242,
    name: "Nivea Cream/Lotion 400ml",
    sku: "NIV",
    price: onlinePrice("NIV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "nivea-cream-lotion-400ml",
    onSpecial: false,
  },
  {
    id: 243,
    name: "Nivea Radiant Cream 400ml",
    sku: "NIVA",
    price: onlinePrice("NIVA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "nivea-radiant-cream-400ml",
    onSpecial: false,
  },
  {
    id: 244,
    name: "Nivea Spray",
    sku: "NIVES",
    price: onlinePrice("NIVES"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "nivea-spray",
    onSpecial: false,
  },
  {
    id: 245,
    name: "Nivea Q10",
    sku: "NVIA",
    price: onlinePrice("NVIA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "nivea-q10",
    onSpecial: false,
  },
  {
    id: 246,
    name: "Oh So Heavenly Lotion 720ml",
    sku: "OHS",
    price: onlinePrice("OHS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "oh-so-heavenly-lotion-720ml",
    onSpecial: false,
  },
  {
    id: 247,
    name: "Oh So Heavenly - 2L",
    sku: "OHSHV",
    price: onlinePrice("OHSHV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "oh-so-heavenly-2l",
    onSpecial: false,
  },
  {
    id: 248,
    name: "Oh  So Heavenly Lotion 1L",
    sku: "OHSL",
    price: onlinePrice("OHSL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "oh-so-heavenly-lotion-1l",
    onSpecial: false,
  },
  {
    id: 249,
    name: "Oh SO Heavenly Cream 450ml",
    sku: "OHSO",
    price: onlinePrice("OHSO"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "oh-so-heavenly-cream-450ml",
    onSpecial: false,
  },
  {
    id: 250,
    name: "Oh So heavenly Q10",
    sku: "OHSOQ",
    price: onlinePrice("OHSOQ"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "oh-so-heavenly-q10",
    onSpecial: false,
  },
  {
    id: 251,
    name: "Olive Oil Spry 250ml",
    sku: "OLV",
    price: onlinePrice("OLV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "olive-oil-spry-250ml",
    onSpecial: false,
  },
  {
    id: 252,
    name: "PlayBoy Roll on",
    sku: "PLA",
    price: onlinePrice("PLA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "playboy-roll-on",
    onSpecial: false,
  },
  {
    id: 253,
    name: "PlayBoy Perfume",
    sku: "PLAY",
    price: onlinePrice("PLAY"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "playboy-perfume",
    onSpecial: false,
  },
  {
    id: 254,
    name: "Roll On Shield",
    sku: "RLS",
    price: onlinePrice("RLS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "roll-on-shield",
    onSpecial: false,
  },
  {
    id: 255,
    name: "Roll On Addidas 50ml",
    sku: "ROLL",
    price: onlinePrice("ROLL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "roll-on-addidas-50ml",
    onSpecial: false,
  },
  {
    id: 256,
    name: "Roll on Nivea - 50ml",
    sku: "ROLNIV",
    price: onlinePrice("ROLNIV"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "roll-on-nivea-50ml",
    onSpecial: false,
  },
  {
    id: 257,
    name: "Roll On Power House 50ml",
    sku: "ROP",
    price: onlinePrice("ROP"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "roll-on-power-house-50ml",
    onSpecial: false,
  },
  {
    id: 258,
    name: "Shower To Shower",
    sku: "SHOW",
    price: onlinePrice("SHOW"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "shower-to-shower",
    onSpecial: false,
  },
  {
    id: 259,
    name: "Shower to Shower Perfume",
    sku: "SHWR",
    price: onlinePrice("SHWR"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "shower-to-shower-perfume",
    onSpecial: false,
  },
  {
    id: 260,
    name: "Skala 200g",
    sku: "SKA",
    price: onlinePrice("SKA"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "skala-200g",
    onSpecial: false,
  },
  {
    id: 261,
    name: "Skala hairFood",
    sku: "SKAL",
    price: onlinePrice("SKAL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "skala-hairfood",
    onSpecial: false,
  },
  {
    id: 262,
    name: "Top Society",
    sku: "TOPS",
    price: onlinePrice("TOPS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "top-society",
    onSpecial: false,
  },
  {
    id: 263,
    name: "Vaseline 450ml",
    sku: "VAS",
    price: onlinePrice("VAS"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-450ml",
    onSpecial: false,
  },
  {
    id: 264,
    name: "Vaseline 250ml",
    sku: "VASE",
    price: onlinePrice("VASE"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-250ml",
    onSpecial: false,
  },
  {
    id: 265,
    name: "v",
    sku: "VASEL",
    price: onlinePrice("VASEL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "hero-4",
    onSpecial: false,
  },
  {
    id: 266,
    name: "Vaseline lips",
    sku: "VASELN",
    price: onlinePrice("VASELN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-lips",
    onSpecial: false,
  },
  {
    id: 267,
    name: "Vaseline 50ml",
    sku: "VASL",
    price: onlinePrice("VASL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-50ml",
    onSpecial: false,
  },
  {
    id: 268,
    name: "Vaseline Cream",
    sku: "VASLN",
    price: onlinePrice("VASLN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-cream",
    onSpecial: false,
  },
  {
    id: 269,
    name: "Vaseline Lotion",
    sku: "VASLNL",
    price: onlinePrice("VASLNL"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-lotion",
    onSpecial: false,
  },
  {
    id: 270,
    name: "Vestline Garlic - 200g",
    sku: "VESTGLC",
    price: onlinePrice("VESTGLC"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vestline-garlic-200g",
    onSpecial: false,
  },
  {
    id: 271,
    name: "Vaseline - 100ml",
    sku: "VSN",
    price: onlinePrice("VSN"),
    unit: "/item",
    category: "Cosmetics",
    subcategory: "Cosmetics",
    image: "vaseline-100ml",
    onSpecial: false,
  },
  {
    id: 272,
    name: "Angel Care Tissue",
    sku: "ANG",
    price: onlinePrice("ANG"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 273,
    name: "Aquafresh - 100ml",
    sku: "AQFRSH",
    price: onlinePrice("AQFRSH"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 274,
    name: "Baby Soft 18s",
    sku: "BABYS",
    price: onlinePrice("BABYS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 275,
    name: "Close Up",
    sku: "CLO",
    price: onlinePrice("CLO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 276,
    name: "Colgate 100ml",
    sku: "COL",
    price: onlinePrice("COL"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 277,
    name: "Utra Pads",
    sku: "DELLP",
    price: onlinePrice("DELLP"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 278,
    name: "Dettol Liquid",
    sku: "DETO",
    price: onlinePrice("DETO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 279,
    name: "Dettol soap",
    sku: "DETT",
    price: onlinePrice("DETT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 280,
    name: "Geisha",
    sku: "GEI",
    price: onlinePrice("GEI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 281,
    name: "HiLife Soap",
    sku: "HIL",
    price: onlinePrice("HIL"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 282,
    name: "hygienix Soap 175g",
    sku: "HYG",
    price: onlinePrice("HYG"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 283,
    name: "Jade Soap",
    sku: "JAD",
    price: onlinePrice("JAD"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 284,
    name: "Kotex pads 10s",
    sku: "KOT",
    price: onlinePrice("KOT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 285,
    name: "Lifebouy",
    sku: "LIFBY",
    price: onlinePrice("LIFBY"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 286,
    name: "Lux Soap",
    sku: "LUX",
    price: onlinePrice("LUX"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 287,
    name: "Oh So Heavenly Gel",
    sku: "OHSOH",
    price: onlinePrice("OHSOH"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 288,
    name: "Kotex Pant Liners",
    sku: "PANT",
    price: onlinePrice("PANT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 289,
    name: "Pads Mix",
    sku: "PDS",
    price: onlinePrice("PDS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 290,
    name: "Period pants",
    sku: "PERI",
    price: onlinePrice("PERI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 291,
    name: "Protex Soap",
    sku: "PROT",
    price: onlinePrice("PROT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 292,
    name: "Private Joy Tissue",
    sku: "PRVT",
    price: onlinePrice("PRVT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 293,
    name: "Romance Soap 50g",
    sku: "ROM",
    price: onlinePrice("ROM"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 294,
    name: "Tissue Single",
    sku: "SAT",
    price: onlinePrice("SAT"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 295,
    name: "Satiskin 2L",
    sku: "SATI",
    price: onlinePrice("SATI"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 296,
    name: "Satiskin 1L",
    sku: "SATSK",
    price: onlinePrice("SATSK"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 297,
    name: "Sona",
    sku: "SON",
    price: onlinePrice("SON"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 298,
    name: "Tissue 4s",
    sku: "TISS",
    price: onlinePrice("TISS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 299,
    name: "TwinSaver Tissue",
    sku: "TWIN",
    price: onlinePrice("TWIN"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 300,
    name: "TwinSaver 9s",
    sku: "TWINS",
    price: onlinePrice("TWINS"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 301,
    name: "Yebo Soap",
    sku: "YBO",
    price: onlinePrice("YBO"),
    unit: "/item",
    category: "Toiletries",
    subcategory: "Toiletries",
    image: "hero-6",
    onSpecial: false,
  },
  {
    id: 302,
    name: "Shumba Soft Drink - 500ml",
    sku: "ADE",
    price: onlinePrice("ADE"),
    unit: "/500ml bottle",
    category: "Beverages",
    subcategory: "Beverages",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 303,
    name: "Cascade Soft Drink - 500ml",
    sku: "CAS",
    price: onlinePrice("CAS"),
    unit: "/500ml bottle",
    category: "Beverages",
    subcategory: "Beverages",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 304,
    name: "Mazoe Orange Crush - 2L",
    sku: "MAZ",
    price: onlinePrice("MAZ"),
    unit: "/2L bottle",
    category: "Beverages",
    subcategory: "Beverages",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 305,
    name: "Peps Cola - 500ml",
    sku: "PEPS",
    price: onlinePrice("PEPS"),
    unit: "/500ml bottle",
    category: "Beverages",
    subcategory: "Beverages",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 306,
    name: "Bokomo Cornflakes - 500g",
    sku: "BOKO",
    price: onlinePrice("BOKO"),
    unit: "/500g box",
    category: "Cereals",
    subcategory: "Cereals",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 307,
    name: "Cerevita Original - 500g",
    sku: "CEREV",
    price: onlinePrice("CEREV"),
    unit: "/500g pack",
    category: "Cereals",
    subcategory: "Cereals",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 308,
    name: "Weetbix Breakfast Cereal - 450g",
    sku: "WETBX",
    price: onlinePrice("WETBX"),
    unit: "/450g box",
    category: "Cereals",
    subcategory: "Cereals",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 309,
    name: "Kefalos Dairy Drink - 200ml",
    sku: "KEF",
    price: onlinePrice("KEF"),
    unit: "/200ml carton",
    category: "Dairy",
    subcategory: "Dairy",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 310,
    name: "Milkit Milkshake - 100ml",
    sku: "MIK",
    price: onlinePrice("MIK"),
    unit: "/100ml bottle",
    category: "Dairy",
    subcategory: "Dairy",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 311,
    name: "Pfuko Buttermilk - 500ml",
    sku: "PFKBT",
    price: onlinePrice("PFKBT"),
    unit: "/500ml bottle",
    category: "Dairy",
    subcategory: "Dairy",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 312,
    name: "Allsorts Sweets - Pack",
    sku: "ALL",
    price: onlinePrice("ALL"),
    unit: "/pack",
    category: "Other Items",
    subcategory: "Other Items",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 313,
    name: "Amazon Cookies - 200g",
    sku: "AMAZ",
    price: onlinePrice("AMAZ"),
    unit: "/200g pack",
    category: "Other Items",
    subcategory: "Other Items",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 314,
    name: "Popcorn Snack Pack",
    sku: "POP",
    price: onlinePrice("POP"),
    unit: "/pack",
    category: "Other Items",
    subcategory: "Other Items",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 315,
    name: "Southern Coating Seasoning - 200g",
    sku: "SOTHCTN",
    price: onlinePrice("SOTHCTN"),
    unit: "/200g pack",
    category: "Seasoning",
    subcategory: "Seasoning",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 316,
    name: "Knorr Soup Sachet",
    sku: "KNOR",
    price: onlinePrice("KNOR"),
    unit: "/sachet",
    category: "Seasoning",
    subcategory: "Seasoning",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
  {
    id: 317,
    name: "Royco Mchuzi Mix",
    sku: "RYC",
    price: onlinePrice("RYC"),
    unit: "/packet",
    category: "Seasoning",
    subcategory: "Seasoning",
    image: DEFAULT_PRODUCT_IMAGE_ID,
    onSpecial: false,
  },
];

const FALLBACK_IMAGE_ID = DEFAULT_PRODUCT_IMAGE_ID;
const IMAGE_OVERRIDES_BY_ID: Record<number, string> = {};

const placeholderIds = new Set(PlaceholderCatalog.map(image => image.id));

const resolveImageId = (product: Product): string => {
  const explicit = product.image?.trim();

  const override = IMAGE_OVERRIDES_BY_ID[product.id];
  if (override && placeholderIds.has(override)) {
    return override;
  }

  if (explicit && !isGenericImageId(explicit) && placeholderIds.has(explicit)) {
    return explicit;
  }

  const slug = slugifyImageId(product.name);
  if (slug && placeholderIds.has(slug)) {
    return slug;
  }

  if (explicit && placeholderIds.has(explicit)) {
    return explicit;
  }

  return FALLBACK_IMAGE_ID;
};

for (const product of products) {
  product.image = resolveImageId(product);
}